### ISSUE TITLE
the fail-fast:true property is not triggered if the config map is not found

### ISSUE THREAD

**Issue by jbkervyn** [spring-cloud/spring-cloud-kubernetes#1016]
I think it would be handy (except if there is another way to do this), to make your application fail when no matching configmap can be found in the namespace. I would expect this to be the behavior of fail-fast. However, this only happens when there is an exception while reading the configmap. If the configmap is not found, no exception is triggered.

**Comment by wind57** [comment]
just dropping a note, if we get to this in the future. may be name such a property `strict`? And treat it just like we treat `profileBasedSources`?

**Comment by wind57** [comment]
I was thinking into a slightly different direction here: what if define profiles that you want to have strictness for? For example:

```
spring:
   cloud:
      kubernetes:
         config:
            sources:
               - name : a
                  strict: false  # this is the default option
                  profiles:
                    - dev
                    - us-west
```

 - This one will try to read (but not fail if these are _not_ present): `a`, `a-dev`, `a-us-west`. 
 - If we change the example above with `strict: true`, it will validate the presence for `a`, `a-dev`, `a-us-west`.
 - If we change the example to:

```
spring:
   cloud:
      kubernetes:
         config:
            sources:
               - name : a
                  strict: true
```

it will validate the presence of `a`, but not enforce `a-dev` and `a-us-west`, `a-kubernetes` (when `dev`, `us-west` and `kubernetes` are active profiles), since you have not provided explicit profiles. 

---

While I am inclined towards this one, the issue comes that we already have a property called `include-profile-specific-sources`. We can leave it as-is, but `profiles` will override it, that is: `profiles` is more specific then `include-profile-specific-sources`. 

I don't mind trying to implement such an approach, but I need @ryanjbaxter thoughts here and yours @jbkervyn too, if you have the time. 

Thank you.

**Comment by wind57** [comment]
note for myself: I started working on this one, and I'll fix one more issue along the way. I've created [this fix](https://github.com/spring-cloud/spring-cloud-kubernetes/pull/1052) that makes sure that `configmap-a` is read before `configmap-a-dev` for example. If there are two profile based configmaps on the other hand:

- `configmap-a`
- `configmap-a-dev`
- `configmap-a-prod`

we do make any distinction (order wise) between  `configmap-a-dev` and `configmap-a-prod`. i.e.: you do not know in what order your properties will come from. 

What I will be fixing also is being in par with profiles `application.yaml` according to Spring documentation : last one will win.

**Comment by jbkervyn** [comment]
I really like your ideas @wind57 . However, what I had in mind was a more simple use-case not going that much into depth with the profiles that you are rightfully pointing out. 

What I was thinking is : as long as you do have a configmap mentionned, there should be at least one hit. So if we do take this strict idea that I do like, it would mean : as long as strict = true, the validation would only succeed if a configmap having value either `a`, `a-dev`, `a-us-west`. It would fail if no configmap matching `a-*` would be found.

Just to ellaborate on the usecase I was initially having when I raised this issue : Simple spring boot app, having no  spring.cloud.kubernetes.config.sources property explicitely set. And by the presense of the depencency, would look for a configmap matching the application.name. In this use-case, I thought that it would make sense to have a failing validation when no configmap would be found. That's why I thought having a at-least logic would make sense.

But I must confess that I do not possess a decent knowledge on the topic, so I'm just sharing, but I do value more your expertise over mine.

Thanks a lot for putting so many thoughts into this :)

**Comment by wind57** [comment]
No worries at all, I liked the idea and I do admit I thought about such a failure of the app when support was added for `fail-fast`. While I agree with you, think about someone who has a `@Profile("dev")` (even better if you think they he/she starts the app with an environment property for those profiles) and strict=true. his/her thoughts are going to go to : "if I have this profile, then there should be a way for me to enforce presence of such a source".

imho, what I propose is nothing more then your proposal + some more use-cases, thus more configurations possible, thus more users that are happy.

To your case btw, simply `strict=true` will suffice indeed and this will be supported. I am almost done with the implementation btw, but it will take a while to properly test this out. thank you for your feedback.

**Comment by jbkervyn** [comment]
I completely agree with your proposal, I was just thinking, maybe we are making it now a bit too complex/flexible. But I eventually think you're right and that this is the way to go.

**Comment by wind57** [comment]
I've hit a bummer :( and I need a bit of help here on the correct approach. Here is the explanation, supposed we have such a config:

```
spring:
  cloud:
    kubernetes:
      config:
        sources:
           - name : a
             include-profile-specific-sources: true
```

and active profiles are `dev`. In such a case we will be reading two configmaps: `a`, `a-dev`. Now let's transpose this to labels instead of a name:

```
spring:
  cloud:
    kubernetes:
      config:
        sources:
           - labels : 
                color: red
              include-profile-specific-sources: true
``` 

And we have two configmaps defined. `a` with labels `color: red` and `a-dev` with labels `color: blue` (yes, their labels do not match). What we currently will be reading is : `a` _and_ `a-dev`, as we do not care if profiles based sources (`a-dev` that is) matches the initial labels. This is a decision I took when creating the functionality about `include-profile-specific-sources`. 

---

Now we add `strict` into the picture:

```
spring:
  cloud:
    kubernetes:
      config:
        sources:
           - name : a
              strict: false
             include-profile-specific-sources: true
             strict-for-profiles:
                - dev
```

In this case, we know upfront the configmaps that we should be reading by name : `a` and `a-dev`. Even if `a` is not present, we are not going to fail, because it has `strict=false`. On the other hand if `a-dev` is missing, we will fail, since `strict-for-profiles=dev`.

And now for labels:

```
spring:
  cloud:
    kubernetes:
      config:
        sources:
              labels: 
                 color: red 
              strict: false
              include-profile-specific-sources: true
              strict-for-profiles:
                - dev
```

We do not know the configmap names upfront, we need to find them by labels first. So we search for labels = `color: red`. Such a configmap is not present, but we do have `strict-for-profiles=dev`. And ... what do we do know? We do not know the name of the configmap to be appended to the profile... 

---

I am inclined to say that my decision about reading `a-dev` (from the previous sample), where I did not care if it matches the initial labels (`color: red`), was wrong. 

Instead I should have not used name at all, when dealing with labeled sources. So for example:

 ```
spring:
  cloud:
    kubernetes:
      config:
        sources:
           - labels : 
                color: red
              include-profile-specific-sources: true
              strict-for-profiles:
                - dev
                - us-west
``` 

there are 3 active profiles : `k8s`, `dev` and `us-west` and 5 configmaps:

- `a` with labels `color: red`
- `b` with labels `color: blue`
- `c-dev` with labels `color: red`
- `d-us-west` with labels `color: red`
- `e-k8s` with labels `color: red` 

 We read all configmaps in the namespace and filter the ones with labels `color: red` (this way we do not touch `b`) and then:

- first get properties from `a`
- then get properties from `e-k8s`. This one comes _before_ `c-dev` and `d-us-west`, since this is kind of optional, as it is not part of `strict-for-profiles`
- then read `c-dev` 
- then read `d-us-west`

The order of the last two are important as it is maintained. My assumption here is that since you have used `strict-for-profiles`, you do not only care about strictness, but about their _order_ too. You can think about it this way:

- anything that is _not_ part of `strict-for-profiles` is read without any order
- anything that _is_ part of `strict-for-profiles` is read in the strict definition order.

I can fix this thing in this PR also, but I need help from @ryanjbaxter .
