### ISSUE TITLE
v2020.0.5+ Stopped loading Configmap running outside a K8s cluster (local).

### ISSUE THREAD

**Issue by digows** [spring-cloud/spring-cloud-kubernetes#1038]
**Describe the bug**
With version 2020.0.4 and earlier, we could load configs from K8s, running locally. 
With version 2020.0.5 and later, the bootstrap ignores the configmap configs, and nothing loads when running locally.

**Sample**
The bootstrap.yml looks like this:

```
#GENERAL
spring:
  application.name: platform

  cloud:
    #KUBERNETES
    kubernetes:
      client:
        namespace: default
      config:
        sources:
          - name: global
          - name: rabbitmq
          - name: postgresql
          - name: mongodb
          - name: jpa-hibernate
          - name: redis
          - name: mail
          - name: firebase
          - name: ${spring.application.name}
```

The relevant dependencies are:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
</dependency>
```
