### ISSUE TITLE
Support services with multiple ports in KubernetesDiscoveryClient

### ISSUE THREAD

**Issue by manderson23** [spring-cloud/spring-cloud-kubernetes#104]
I have a zookeeper Service configured as follows:
```
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-1
```
In this case the K8 client finds an Endpoint for `zoo1` where the `EndpointSubset` has one address and three ports.

A call to `discoveryClient.getInstances("zoo1")` returns the `leader` port only whereas I would like the `client` port.

Should `KubernetesDiscoveryClient` return three `ServiceInstance` in this case? One for each port?
