### ISSUE TITLE
KubernetesCatalogWatch clarification

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1143]
After understanding a bit what our `KubernetesCatalogWatch` does, I have some doubts about its correctness. 

Internally, what we do at the moment is:

```
endpoints.stream().map(Endpoints::getSubsets)
	.filter(Objects::nonNull).flatMap(List::stream).map(EndpointSubset::getAddresses)
	.filter(Objects::nonNull).flatMap(List::stream).map(EndpointAddress::getTargetRef)
	.filter(Objects::nonNull).map(x -> new EndpointNameAndNamespace(x.getName(), x.getNamespace()))
	.sorted(Comparator.comparing(EndpointNameAndNamespace::endpointName, String::compareTo)).toList();
```

We ultimately get a `List<EndpointAddress>` and look-up what each `EndpointAddress` maps to. An example should make this far clearer, suppose these yamls:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  selector:
    matchLabels:
      app: busybox
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: busybox
        version: v1
    spec:
      containers:
        - name: busybox
          image: arm64v8/busybox:latest
          command: ["/bin/sh"]
          args: ["-c", "sleep 100000"]
```

and a service:

```
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
spec:
  selector:
    app: busybox
  type: ClusterIP
  ports:
    - name: busybox-port
      port: 8080
      targetPort: 80
```

Pretty simple: a deployment with 3 busybox replicas and a service for it. 

---

For such a case, our implementation is going to return a `HeartbeatEvent` with a List of 3 Objects, something like:

```
busybox-85447db8ff-dc4jt, default
busybox-85447db8ff-gz8lf, default
busybox-85447db8ff-p5jj7, default
```

I can't see how such a response is useful for someone who listens to these heartbeats, as it simply shows the pods of a certain service (retrieved and filter via `endpoints`, but still).

@ryanjbaxter do you happen to have some time to bring some clarifications may be? thank you!
