### ISSUE TITLE
403 when starting server

### ISSUE THREAD

**Issue by codex70** [spring-cloud/spring-cloud-kubernetes#1156]
**Describe the bug**
When service discovery is enabled, I get the following error on startup:

```
io.kubernetes.client.openapi.ApiException: class V1Status {
    apiVersion: v1
    code: 403
    details: class V1StatusDetails {
        causes: null
        group: null
        kind: services
        name: null
        retryAfterSeconds: null
        uid: null
    }
    kind: Status
    message: services is forbidden: User \"system:serviceaccount:test:test-service\" cannot list resource \"services\" in API group \"\" at the cluster scope
    metadata: class V1ListMeta {
        _continue: null
        remainingItemCount: null
        resourceVersion: null
        selfLink: null
    }
    reason: Forbidden
    status: Failure
}
```

The service account is created with permissions as stated in the documentation:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets", "namespaces"]
    verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
subjects:
  - kind: ServiceAccount
    name: test
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
```

And the application.yaml contains the following:
```
    cloud:
      kubernetes:
        discovery:
          enabled: true
          all-namespaces: true
```

Is there any way the service account can read the services in all namespaces, or do I actually have to create a role for the service account in each separate namespace? Potentially we will have hundreds of namespaces with each application deployed to its own namespace.

If I set `all-namespaces` to false, it works, but obviously it can only find the single service that's in the corresponding namespace (basically it can only find itself).

**Comment by codex70** [comment]
I've actually tried it with cluster role (both instead of and as well as the role):
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-discovery-client
  namespace: default
rules:
  - apiGroups: ["", "extensions", "apps"] # "" indicates the core API group
    resources: ["services", "pods", "configmaps", "endpoints", "namespaces"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-discovery-client-binding
subjects:
  - kind: ServiceAccount
    name: test
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: service-discovery-client
  apiGroup: ""

```
It doesn't seem to make any difference.
