### ISSUE TITLE
Upgrading to Spring Boot 3, config does not load - Cannot enhance @Configuration KubernetesClientAutoConfiguration

### ISSUE THREAD

**Issue by codex70** [spring-cloud/spring-cloud-kubernetes#1169]
**Describe the bug**
I'm upgrading an existing project to spring boot 3 and using the spring-cloud-kubernetes-3.0.0-RC3 dependency.

When I start the application it is no longer loading the configuration and I get the following error message:
```
Cannot enhance @Configuration bean definition 'org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
```

**Sample**
The is the configuration I am using:
```
spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
        all-namespaces: true # Servlet container configuration
      reload:
        period: 1000
        enabled: true
        mode: event
      config:
        enabled: true
        name: test-service
        sources:
          - name: test-service
```

Not sure what other code would be useful to supply, I really don't know where to start with this. Spent the past few days googling, and I'm sure I'm missing something obvious.

**Comment by wind57** [comment]
Can you create a git repo with all the needed details? I mean, a real maven/gradle project and instructions on how to build and deploy it. If you do, I will gladely take a look.

**Comment by codex70** [comment]
Thanks, I will try to see if I can create a project that replicates the issue. Unfortunately I cannot share the current source code, but can probably create a stripped down version.

**Comment by codex70** [comment]
OK, I've got a fairly clean repository setup that I believe is still causing the problem (at least it is in my cluster).

https://github.com/codex70/spring-boot-service

There's the application code, which requires java 17+ and gradle 7.6. I've also included a helm chart which I use to deploy the application. Hopefully it will all still work and give you an idea of where I'm seeing problems.

**Comment by codex70** [comment]
Also, an interesting note, I am able to configure the application using json stored in a ConfigMap and passing the following  environment value:
```
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev,kubernetes
    - name: SPRING_APPLICATION_JSON
      valueFrom:
        configMapKeyRef:
          name: spring-config
          key: application.json

```

**Comment by codex70** [comment]
@wind57,,the app starts without problem, it just doesn't load the ConfigMap so no configuration variables are loaded. This is a bit of a blocker as we use a CICD pipeline which inserts secrets using the helm template. There are work arounds, but they are nowhere near as nice.

**Comment by codex70** [comment]
There are no errors when starting the application to show why the ConfigMap is not loaded, the only thing  can see is the above message which might explain why it's not working. The CM does load correctly with spring boot 2.x

**Comment by wind57** [comment]
I am really confused what the problem is then, because your first post in this issue says something to do with `reload`, but now something to do with a configmap.

So what exactly are you trying to achieve (again, please make it as simple as possible :) ) and what is the problem? You have an app that is trying to read from a ConfigMap for its properties?

**Comment by codex70** [comment]
Hi thanks @wind57, there was nothing specific about reload,

What I am trying to achieve is loading a PropertySource using a configmap:
https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#kubernetes-propertysource-implementations

**Comment by codex70** [comment]
In my code, there is a helm template: `application.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name }}
  labels:
    version: {{ .Values.applicationYaml.info.app.version }}
    app: {{ .Values.application.name }}
data:
{{- with .Values.applicationYaml }}
  application.yml: |-
{{ toYaml . | indent 4 }}
{{- end }}
```

which should load the following application.yaml:
```
applicationYaml:
  spring:
    cloud:
      kubernetes:
        discovery:
          enabled: "true"
  server:
    ssl:
      enabled: false
  info:
    app:
      version: 1.0.0
```
but this doesn't work for me.

**Comment by wind57** [comment]
Excellent. Then please provide a simple reproducible example, strip down helm, strip down security, everything that is not essential. This should be very simple: an app, a deployment, a configmap; steps to reproduce.

**Comment by codex70** [comment]
OK, will work on it and let you know.

**Comment by codex70** [comment]
Hi @wind57, I've now stripped down the application, I think it's now as minimal as it can be.

I've also deleted the helm charts and created a directory with a deployment and a configmap file, together with a service account, in case it is needed. I haven't added roles and role binding to keep it simple.

In my setup I'm still seeing the same issue, the configmap is not being read and the application is deployed on the default port of 8080, not the port 8088 provided in the ConfigMap:
```
2022-12-12T09:27:17.996Z  INFO 1 --- [           main] o.s.c.a.ConfigurationClassPostProcessor  : Cannot enhance @Configuration bean definition 'org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'.
2022-12-12T09:27:18.135Z  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=2134b040-c28c-38d8-97d1-e0dd2c9590e9
2022-12-12T09:27:18.408Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2022-12-12T09:27:18.416Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2
```

**Comment by wind57** [comment]
First things first: thank you for making a reproducible example. This has triggered two issues on our side, one small, one bigger. 

The "bigger" has to do with logging. The way we have logging currently implemented, you can't really see what is going on. We will fix this relatively soon.

Now to your issue at hand: 

I think that you are confusing `application.yaml` and `bootstrap.yaml` to begin with.
In your sample you define your sources in `application.yaml` and that is not correct - that is not going to work. You need to put them in `bootstrap.yaml` + enable bootstraping. You might want to take a look at the [updated documentation](https://docs.spring.io/spring-cloud-kubernetes/docs/3.0.0-RC3/reference/html/#kubernetes-propertysource-implementations)

If you read carefully that documentation and conform to it, you can indeed put your settings in `application.yaml` (since your app name is the same as the configmap name), here is a slightly simpler version (notice that I've dropped a few things from your initial one):

```
spring:
  config:
    import: "kubernetes:"
  application:
    name: spring-boot-service

server:
  ssl:
    enabled: false
  port: 8080

```

But if you run this, "nothing" will happen. Actually nothing will be visible to you in logs (because of that problem of ours with logging), in reality though (this is what you should see and will once we fix the issue with logging):

```
2022-12-13T12:37:51.881Z  WARN 1 --- [           main] o.s.c.k.commons.config.ConfigUtils       : {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:spring-boot:sp
ring-boot-service\" cannot list resource \"configmaps\" in API group \"\" in the namespace \"spring-boot\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}
. Ignoring.

java.lang.RuntimeException: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps is forbidden: User \"system:serviceaccount:spring-boot:spring-boot-service\" cannot list resource \"configmaps\" in API group \
"\" in the namespace \"spring-boot\"","reason":"Forbidden","details":{"kind":"configmaps"},"code":403}
```

---

If I configure correct RBAC:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-role
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
```

and 


```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: spring-cloud-kubernetes-core-k8s-client-it
  name: spring-cloud-kubernetes-role-binding
  namespace: spring-boot
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: cluster-role
subjects:
  - kind: ServiceAccount
    name: spring-boot-service
    namespace: spring-boot
```

deploy again and will see:

```
2022-12-13T12:48:42.073Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8088 (http)
```
