### ISSUE TITLE
Service label filter not working

### ISSUE THREAD

**Issue by mirza-ali-ctct** [spring-cloud/spring-cloud-kubernetes#1228]
**Describe the bug**
This bug is the related to  https://github.com/spring-cloud/spring-cloud-kubernetes/issues/810 but in a different version. The service labels filter is being ignored and all apps are listing in all namespaces.

**Sample**
```yaml
apiVersion: v1
data:
  application.yaml: |-
    logging:
      level:
        root: DEBUG

    management:
      scheme: http
    server:
      forward-headers-strategy: NATIVE
    spring:
      cloud:
        kubernetes:
          discovery:
            enabled: true
            all-namespaces: false
            service-labels:
              "[app.kubernetes.io/instance]": token-svc
      boot:
        admin:
          ui:
            public-url: http://sbac.qa.apps.ctct.io/
          discovery:
            converter:
              management-context-path: /actuator
          instance-auth:
            enabled: true
            default-user-name: ${SBAC-DEFAULT-USER}
            default-password: ${SBAC-DEFAULT-PASSWORD}
      management:
        server:
          port: 80
        endpoints:
          web:
            base-path: /
```

These are the maven dependeicies we are using 
```xml
<dependencies>
        <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>spring-boot-admin-starter-server</artifactId>
            <version>2.7.10</version>
        </dependency>
        <!-- broken refresh, https://github.com/spring-cloud/spring-cloud-kubernetes/issues/745
        <dependency>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-starter-kubernetes-client-all</artifactId>
          <version>2.0.3</version>
        </dependency>
        -->
        <!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-kubernetes-client-all -->
        <!--    <dependency>-->
        <!--      <groupId>org.springframework.cloud</groupId>-->
        <!--      <artifactId>spring-cloud-starter-kubernetes-client-all</artifactId>-->
        <!--      <version>2.1.5</version>-->
        <!--    </dependency>-->
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcpkix-jdk15on</artifactId>
            <version>1.69</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk15on</artifactId>
            <version>1.69</version>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-ext-jdk15on</artifactId>
            <version>1.69</version>
        </dependency>


        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-kubernetes-fabric8-discovery</artifactId>
            <version>2.1.5</version>
        </dependency>
    </dependencies>
```
