### ISSUE TITLE
kubernetes-leader-election-example: service not elected as leader

### ISSUE THREAD

**Issue by shoner-sul** [spring-cloud/spring-cloud-kubernetes#1277]
**Describe the bug**
Following https://github.com/spring-cloud/spring-cloud-kubernetes/tree/main/spring-cloud-kubernetes-examples/kubernetes-leader-election-example , service is not receiving leadership even without replication. Any additional settings required?

[shoner@shoner kubernetes-leader-election-example]$ kubectl apply -f deploy.yml 
service/kubernetes-leader-election-example created
serviceaccount/kubernetes-leader-election-example created
rolebinding.rbac.authorization.k8s.io/kubernetes-leader-election-example:view created
role.rbac.authorization.k8s.io/namespace-reader created
deployment.apps/kubernetes-leader-election-example created

[shoner@shoner kubernetes-leader-election-example]$ minikube service kubernetes-leader-election-example --url
http://192.168.49.2:31706

[shoner@shoner kubernetes-leader-election-example]$ SERVICE_URL=$(minikube service kubernetes-leader-election-example --url)
[shoner@shoner kubernetes-leader-election-example]$ curl $SERVICE_URL
I am 'kubernetes-leader-election-example-795dc76c6b-nfbvx' but I am not a leader of the 'world'[shoner@shoner kubernetes-leader-election-example]$ curl $SERVICE_URL
I am 'kubernetes-leader-election-example-795dc76c6b-nfbvx' but I am not a leader of the 'world'[shoner@shoner kubernetes-leader-election-example]$ curl $SERVICE_URL
I am 'kubernetes-leader-election-example-795dc76c6b-nfbvx' but I am not a leader of the 'world'[shoner@shoner kubernetes-leader-election-example]$ curl $SERVICE_URL
I am 'kubernetes-leader-election-example-795dc76c6b-nfbvx' but I am not a leader of the 'world'[shoner@shoner kubernetes-leader-election-example]$ kubectl get pods
NAME                                                  READY   STATUS    RESTARTS   AGE
kubernetes-leader-election-example-795dc76c6b-nfbvx   1/1     Running   0          7m32s
[shoner@shoner kubernetes-leader-election-example]$ curl $SERVICE_URL
I am 'kubernetes-leader-election-example-795dc76c6b-nfbvx' but I am not a leader of the 'world'[shoner@shoner kubernetes-leader-election-example]$ 

**Sample**
Used https://github.com/spring-cloud/spring-cloud-kubernetes/tree/main/spring-cloud-kubernetes-examples/kubernetes-leader-election-example in main branch as is, with two minor modifications below. "deploy.yml" file in the description above is a file created as instructed under "You can then deploy the application using the following yaml."
1. Changed service type in YAML to NodePort, as discussed in https://github.com/spring-cloud/spring-cloud-kubernetes/issues/1257
2. Due to 404 error, I modified LeaderController.java: @ GetMapping -> @ GetMapping({ "", "/" })

**Comment by ryanjbaxter** [comment]
Can try replacing the role in the deploy YAML with this

```

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      namespace: default
      name: namespace-reader
    rules:
      - apiGroups: ["", "extensions", "apps"]
        resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
        verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```
