### ISSUE TITLE
Kubernetes service discovery doesn't work along with simple discovery service

### ISSUE THREAD

**Issue by rechandler12** [spring-cloud/spring-cloud-kubernetes#1286]
**Describe the bug**
I want to have 2 layers of discovery service: Kubernetes discovery client and simple discovery client. It's working with eureka (local dev env) and it was working before 3.0 spring-cloud-kubernetes.

**Sample**
Here's my configs:
```
spring:
  config:
    import: "kubernetes:"
  cloud:
    kubernetes:
      discovery:
        service-labels:
          "[app.kubernetes.io/part-of]": asdf
      loadbalancer:
        mode: SERVICE
```

```
spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            xyz:
              - uri: http://xyz/
            xyz-custom:
              - uri: http://xyz/
```

and I've got:
`Load balancer does not contain an instance for the service xyz-custom`
