### ISSUE TITLE
Properties with square brackets in ConfigMaps for lists

### ISSUE THREAD

**Issue by taxone** [spring-cloud/spring-cloud-kubernetes#1314]
How can I define the values of a property of type **List** using [ConfigMaps  PropertySource](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#configmap-propertysource)?
This my Configuration class:

![image](https://user-images.githubusercontent.com/6004991/233373177-5774763c-9d91-43b1-a112-1f606bef2f55.png)

and I would like to create a ConfigMap like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample
data:
  sample.my-configs[0].a-value: hello
  sample.my-configs[1].a-value: world
```

But using square brackets for keys in ConfigMaps is illegal according to specifications.

Using underscores does not work ([as described here](https://github.com/spring-projects/spring-boot/wiki/Relaxed-Binding-2.0#lists-1)), probably because the properties retrieved by Spring Cloud Kubernetes are not environment variables but real properties.

In Spring Cloud Kubernetes I found only examples about simple properties, but it seems that there aren't examples about lists.
Thanks.

**Comment by taxone** [comment]
Thank you for your help.
No, I can't and I explain  way describing my use case.
We use [Kustomize](https://github.com/kubernetes-sigs/kustomize) and the application.yaml is defined in the base configuration:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample
data:
  application.yml: |-
    sample:
      foo: bar
      my-configs: 
      - a-value: hello
      - a-value: world
```

in the production overlay (for example) I need to override just the _my-configs_ property. I tried this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample
data:
  sample.my-configs_0_.a-value: hello
  sample.my-configs_1_.a-value: world
```
or also this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample
data:
  SAMPLE_MY_CONFIGS_0_.A-VALUE: hello
  SAMPLE_MY_CONFIGS_1_.A-VALUE: world
```

but none of the above configurations work.

**Comment by ryanjbaxter** [comment]
Isn't Kustomize then taking the overalay and generating the configmap?

Why not use YAML in the overlay?

Maybe a sample would help.

**Comment by taxone** [comment]
Hi Ryan,
Kustomize executes a "merge" of the base configuration and an overlay.
For example, suppose that this is the ConfigMap defined in the base configuration:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample
data:
  application.yml: |-
    sample:
      foo: hello
      bar: world
```

and in the **production** overlay we have:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample
data:
  sample.foo: good morning
```

The actual resulting configuration will be a ConfigMap named **spring-kubernetes-sample** with the entries below:

```
* sample.foo: good morning
* application.yml: |-
    sample:
      foo: hello
      bar: world
```

So, the configuration properties of my Spring application will get these final values for the properties:

* sample.foo: good morning
* sample.bar: world

As you can see, the property sample.foo defined in the _application.yaml_ of the base overlay is overridden by the key defined in the production overlay when the ConfigMap is loaded by Spring Cloud Kubernetes.
This works very well with simple properties or properties of type **Map** but it does not allow to override List properties.
Please let me know if you need a code sample or the example above is enough.
Thank you very much.

**Comment by wind57** [comment]
@ryanjbaxter would like to chime in and get your input on this issue a bit. 

we can solve this, on our side, kind of. At the moment in `ConfigMapPropertySourceLocator`, we do:


```
	@Override
	public PropertySource<?> locate(Environment environment) {
		if (environment instanceof ConfigurableEnvironment env) {

			CompositePropertySource composite = new CompositePropertySource("composite-configmap");
			if (this.properties.enableApi()) {
				Set<NormalizedSource> sources = new LinkedHashSet<>(this.properties.determineSources(environment));
				LOG.debug("Config Map normalized sources : " + sources);
				sources.forEach(s -> composite.addFirstPropertySource(getMapPropertySource(s, env)));
			}

			addPropertySourcesFromPaths(environment, composite);

			cache.discardAll();
			return composite;
		}
		return null;
	}
```

but we could:


```
	@Override
	public PropertySource<?> locate(Environment environment) {
		if (environment instanceof ConfigurableEnvironment env) {

			CompositePropertySource composite = new CompositePropertySource("composite-configmap");
			if (this.properties.enableApi()) {
				Set<NormalizedSource> sources = new LinkedHashSet<>(this.properties.determineSources(environment));
				LOG.debug("Config Map normalized sources : " + sources);
				sources.forEach(s -> {
					MapPropertySource propertySource = getMapPropertySource(s, env);
					composite.addPropertySource(propertySource);
					Map<String, Object> properties = propertySource.getSource();
					((ConfigurableEnvironment) environment).getPropertySources().addAfter(
						StandardEnvironment.SYSTEM_ENVIRONMENT_PROPERTY_SOURCE_NAME,
							new SystemEnvironmentPropertySource("configmap-as-env-" +
								StandardEnvironment.SYSTEM_ENVIRONMENT_PROPERTY_SOURCE_NAME, properties));
				});
			}

			addPropertySourcesFromPaths(environment, composite);

			cache.discardAll();
			return composite;
		}
		return null;
	}
```

and then it would work - the properties would be wired correctly in the `@ConfigurationProperties` (I wrote a small test to prove that for myself)...

**Comment by taxone** [comment]
Cool!!!
Thank you very much.
Do you think that your fix will be included in one of the next releases of Spring Cloud Kubernetes?

**Comment by wind57** [comment]
This relies on un-documented order or property sources + create a system property source, which might be a problem. So the above might as-well be rejected, which would make sense on some level.

**Comment by ryanjbaxter** [comment]
I guess I can see possibly adding support for system properties in configmap and secrets.

However I also think a slightly different approach to what you are doing could accomplish the same thing with the use of spring profiles

`kustomization/base/config.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample
data:
  application.yaml: |-
    sample:
      foo: bar
      my-configs:
        - a-value: hello
        - b-value: world
```
`kustomization/base/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
```

`kustomization/production/kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - prod-config.yaml
```
`kustomization/production/prod-config.yaml`
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample-production
data:
  application-production.yaml: |-
    sample:
      my-configs:
        - a-value: hello-overlay
```

running `kustomize build ./production` results in 
```
apiVersion: v1
data:
  application.yaml: |-
    sample:
      foo: bar
      my-configs:
        - a-value: hello
        - b-value: world
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample
---
apiVersion: v1
data:
  application-production.yaml: |-
    sample:
      my-configs:
        - a-value: hello-overlay
kind: ConfigMap
metadata:
  name: spring-kubernetes-sample-production
```

If the application specified `spring.application.name=spring-kubernetes-sample` and activated the `production` profile that would override the property `sample.my-configs[0].a-value` to be `hello-overlay` (i believe)

The other option is to not use profiles and instead using `spring.cloud.kubernetes.config.sources` and rely on the ordering of the sources to override configuration properties.

So I think there is an enhancement here, but IMO its low priority because we have a couple of options to accomplish what you are trying to do (with much cleaner syntax as well IMO).
