### ISSUE TITLE
Configuration watcher should not set reload to true

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1324]
In the configuration watcher project, we have this part of yaml:

```
spring:
  config:
    import: "kubernetes:"
  application:
    name: spring-cloud-kubernetes-configuration-watcher
  cloud:
    kubernetes:
      reload:
        enabled: true
```

Specifically `spring.cloud.kubernetes.reload.enabled=true`, which means that the app will restart twice, one from "plain" watcher and one as an event that is published.

We should disable this flag in the configuration watcher image.
