### ISSUE TITLE
Paths differ in how we treat them in configmaps and secrets

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1335]
Consider the case when you have enabled:

```
spring:
  cloud:
    kubernetes:
       config:
          paths:
            - /tmp/application.properties
```

and:

```
spring:
  cloud:
    kubernetes:
       secrets:
          paths:
            - /tmp
```

The first one expects an exact path for a config file, the second can actually "walk", see [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/SecretsPropertySourceLocator.java#L117).

While you can specify:

```
spring:
  cloud:
    kubernetes:
       secrets:
          paths:
            - /tmp/application.properties
```

walking is still an option, unlike in config maps. 

In its fairness, this is documented correctly. First:

> `spring.cloud.kubernetes.config.paths` expects a List of full paths to each property file, because directories are not being recursively parsed

and:

> When enabled, the `Fabric8SecretsPropertySource` looks up Kubernetes for `Secrets` from the following sources:

> Reading recursively from secrets mounts

Still, it feels a bit weird that Secrets are able to walk a directory and ConfigMaps can't. 

Should this be unified and should we make ConfigMaps directories "walkable" too?

Or may be in reverse, make Secrets "unwalkable"? The problem in providing support for `Files::walk` is order. This method does not define any order of reading files, so if you have mounted `application.yaml` and `application-prod.yaml`, there might be potential issues from run to run.
