### ISSUE TITLE
ConfigMapConfigProperties is not mapping sources or name from my application.yaml

### ISSUE THREAD

**Issue by rob-64** [spring-cloud/spring-cloud-kubernetes#1345]
**Describe the bug**
Cannot get spring cloud config to use spewcify config maps with 3x. I noticed that the ConfigMapConfigProperties has switched to a record instead of pojo with 3x, unsure if this is the problem.

spring cloud kubernetes commons 3.0.2 via fabric8 config

**Sample**
```
spring:
  application.name: spring-boot-admin
  boot:
    admin:
      discovery:
        instances-metadata:
          "[spring.boot.admin/discoverable]": true
  cloud:
    kubernetes:
      reload:
        enabled: true
      config:
        name: spring-k8s
        sources:
          - name: core-spring
          - name: shared-services-spring
```
