### ISSUE TITLE
Warning about deprecated config paths when uniquePaths is empty

### ISSUE THREAD

**Issue by lmcmipl** [spring-cloud/spring-cloud-kubernetes#1358]
**Describe the bug**
Spring Cloud 2022.0.3

**Sample**
My config is using  spring.config.import, and uniquePaths =[],  yet the following WARN is repeated every 15s in the logs:

```
WARN s.c.k.c.c.ConfigMapPropertySourceLocator : path support is deprecated and will be removed in a future release. Please use spring.config.import
DEBUG s.c.k.c.c.ConfigMapPropertySourceLocator : paths property sources : []
```

**Comment by ryanjbaxter** [comment]
Can you provide the full configuration for your application?

@wind57 FYI

**Comment by lmcmipl** [comment]
> Can you provide the full configuration for your application?
> 
> @wind57 FYI

Sure. 

The application.yaml has these profiles. First profile with spring.cloud features disabled for local devs, and second one for k8s deployments. 

```
spring:
  application:
    name: tata
  cloud:
    loadbalancer:
      enabled: false
    kubernetes:
      config:
        enabled: false
      reload:
        enabled: false
---
spring:
  config:
    activate.on-profile: toto
    import: "kubernetes:"
  cloud:
    loadbalancer:
      enabled: true
    kubernetes:
      config:
        enabled: true
        includeProfileSpecificSources: false
      reload:
        enabled: true
        mode: polling
        period: 15000
```

My helmchart config-map has this application.yaml for environment specific deployments in k8s: 

```
apiVersion: v1
kind: ConfigMap
metadata:
 name: tata 
data:
  application.yaml: |-
    spring:
      config.activate.on-profile: myenv
```

And my helmchart deployment sets this environment variable:

```
SPRING_PROFILES_ACTIVE=toto,myenv
```
