### ISSUE TITLE
ConfigMap cannot be read even when it exists.

### ISSUE THREAD

**Issue by tabiul** [spring-cloud/spring-cloud-kubernetes#138]
I am getting the error message
Can't read configMap with name: [cm-core-api-app-config] in namespace:[tmahmood]. Ignoring when the configMap cm-core-api-app-config exists.

When I do kubectl get configmap --namespace tmahmood then I can see the name cm-core-api-app-config

Any idea why the configMap cannot be read?

**Comment by stela** [comment]
@tabiul There ought to be an exception after that message. In my case it complains:
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: ... Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. configmaps ... 

For me it worked fine on minikube on macOS but fails on a "real" Linux kubeadm-installed single-node kubernetes installation.

As a workaround you can mount a ConfigMap as a volume, see https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume, just like a Secret, however it seems the spring-cloud-kubernetes doesn't explicitly support that for ConfigMaps yet, see SecretsPropertySource versus ConfigMapPropertySource, the former allows configuring filesystem paths to be scanned. Would be good to extend ConfigMapPropertySource IMHO to allow that.

As a "hack", I was able to mount a ConfigMap volume next to my Secrets, however not really ideal to mix up the two types of settings.

You can also expose a ConfigMap as environment variables, either one-by-one or a complete ConfigMap in one go, see https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-pod-environment-variables-using-configmap-data

**Comment by spencergibb** [comment]
Closing this due to inactivity. Please re-open if there's more to discuss.

**Comment by anwarchk** [comment]
@spencergibb wondering if this was resolved in any know releases ? I am seeing the same issue :`WARN  [scheduling-1] org.springframework.cloud.kubernetes.config.ConfigMapPropertySource: Can't read configMap with name: [spring-boot-k8s-recipes] in namespace:[default]. Ignoring`

**Comment by anwarchk** [comment]
My `bootstrap.yml` 

```
spring:
  application:
    name: spring-boot-k8s-recipes
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 10000
      config:
        sources:
          - name: ${spring.application.name}
        namespace: default
```

**Comment by spencergibb** [comment]
Have you looked at the docs on security (site is down right now, but here is the source: https://github.com/spring-cloud/spring-cloud-kubernetes/blob/master/docs/src/main/asciidoc/security-service-accounts.adoc)

**Comment by anwarchk** [comment]
I did @spencergibb . In addition to the example provided in this repo, I also looked at the example application provided here :  https://github.com/fabric8-quickstarts/spring-boot-camel-config.git where it defines the required ServiceAccount and RoleBinding to be able to watch ConfigMaps. I applied the same concepts to the example provided by this project and added the RBAC details required, but still no luck.

**Comment by spencergibb** [comment]
@geoand @salaboy or @ryanjbaxter will have to comment further

**Comment by anwarchk** [comment]
@spencergibb I got it working :-) Had to tweak the `ServiceAccount` role binding as follows : 
```
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "boot-reload-config"
roleRef:
  # Add the view role to the service account
  name: "view"
  kind : ClusterRole
subjects:
  - kind: "ServiceAccount"
    name: "boot-reload-config"
    namespace: default
```
I would like to contribute some documentation about this so that the next person won't have to spend several hours like I did :-)

**Comment by geoand** [comment]
@amwarchk just curious, what part of the RoleBinding did you need to tweak?

**Comment by anwarchk** [comment]
@geoand  Here is the diff from the Fabric8 sample RBAC config to what worked for me. I am using K8s 1.14

```
apiVersion: "v1"
kind: "RoleBinding"
metadata:
  name: "qs-camel-config"
roleRef:
  # Add the view role to the service account
  name: "view"
subjects:
  - kind: "ServiceAccount"
    name: "qs-camel-config"
```

to

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: config-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    name: config-reader
    namespace: default
```
