### ISSUE TITLE
Custom primary-port-name with loadbalancer.mode SERVICE makes service non discoverable

### ISSUE THREAD

**Issue by SabareeshGC** [spring-cloud/spring-cloud-kubernetes#1419]
**Describe the bug**
Spring boot 3.1.2
Spring Cloud 2022.0.4

When using custom primary port name such as http-api in combination WITH spring.cloud.kubernetes.loadbalancer.mode: SERVICE causes the service to be non discoverable. 

> Works fine when in POD mode

> OR Works fine when using primary-port-name label as http 

Service is listed on discoveryClient but when trying to get it from Loadbalancer it return an items in the list with empty value. Originally experienced this issue with feign was not able find a service instance with name accounts

```
@Autowired
private LoadBalancerClientFactory loadBalancerClientFactory;

ServiceInstanceListSupplier supplier = loadBalancerClientFactory.getInstance("accounts", ServiceInstanceListSupplier.class);
List<ServiceInstance> list = supplier.get().collectList().block().stream().findAny().get();
```

```
kind: Service
apiVersion: v1
metadata:
  name: accounts
  namespace: default
  labels:
    app.kubernetes.io/name: accounts
    port.management: '8081'
    primary-port-name: http-api
    secured: 'false'
    springBoot: 'true'
  annotations:
    boot.spring.io/actuator: http://:8081/actuator
    meta.helm.sh/release-name: sk
    meta.helm.sh/release-namespace: sab-ws
spec:
  ports:
    - name: http-api
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-actuator
      protocol: TCP
      port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: accounts
  clusterIP: 172.16.210.8
  clusterIPs:
    - 172.16.210.8
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
status:
  loadBalancer: {}
```
