### ISSUE TITLE
It should discover new replicas

### ISSUE THREAD

**Issue by yleguern** [spring-cloud/spring-cloud-kubernetes#1581]
Hello

**Describe the bug**
spring-cloud-kubernetes (fabric8) version: `3.1.0`
spring-cloud version: `2023.0.0`
spring-boot-admin version: `3.2.1`
spring-boot version: `3.2.2`

I'm using `spring-boot-admin` with `spring-cloud-kubernetes` to discover running services and pods on my cluster.  
It's working well when I start `spring-boot-admin` (it discovers all services and pods) but if I had new replicas : nothing changes even after several hours.
However if I deploy a new service (even on an another namespace) everything gets discovered.

```yaml
spring:
    cloud:
        kubernetes:
            client:
                no-proxy: ${KUBERNETES_SERVICE_HOST}
            discovery:
                namespaces:
                    - xxxx
                    - yyyy
                use-endpoint-slices: true
                service-labels:
                    discovery: sba-actuator
```
