### ISSUE TITLE
gateway+kubernetes配置自动发现服务正常，但服务内部请求时携带服务id不一致

### ISSUE THREAD

**Issue by 445990772** [spring-cloud/spring-cloud-kubernetes#1667]
1. 使用spring-cloud-starter-kubernetes-fabric8 ，版本如下
![image](https://github.com/spring-cloud/spring-cloud-kubernetes/assets/9440839/6f2d98d3-3b3e-4bc7-8d81-ec739bf0da3b)
2.  spring-cloud-kubernetes 配置
```yaml
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    kubernetes:
      loadbalancer:
        mode: SERVICE
      discovery:
        enabled: true
        all-namespaces: false
        primary-port-name: http          #配置为端口名称
```
3. spring-cloud-gateway配置
```yaml
spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/system/config/**,/system/version
         ...
#         其他几个服务的网关配置
```
ps: 我在k8s上部署时分别给几个微服务设置了新的服务名 
authentication-service 对应 auth-cloud
file-service 对应 file-cloud

4. 当我使用前端请求 `system/config/front` 和 `/system/version` 时出现不同的结果，如下图
![image](https://github.com/spring-cloud/spring-cloud-kubernetes/assets/9440839/cd350a05-c681-420a-bb21-5b37f8cf23bc)
![image](https://github.com/spring-cloud/spring-cloud-kubernetes/assets/9440839/03ace066-8392-49f8-8493-f577b2baeac7)
![image](https://github.com/spring-cloud/spring-cloud-kubernetes/assets/9440839/db0e3b39-c550-48a8-b18d-16b10a834dae)

5. 我尝试调试，在底层代码内发现
![image](https://github.com/spring-cloud/spring-cloud-kubernetes/assets/9440839/5bfb4bcc-6d18-4877-aa1b-071872a01b1d)
在红框处 两个接口得到的结果不一样，返回200的接口能获取route信息，如下
![image](https://github.com/spring-cloud/spring-cloud-kubernetes/assets/9440839/a14f9d9a-e229-4187-9d39-8615cc959e12)
但503的接口获取不到route信息，默认获取了源地址，如下
![image](https://github.com/spring-cloud/spring-cloud-kubernetes/assets/9440839/4382ea7e-dac8-4241-8d2a-641f7a341b1c)

有点疑惑该如何解决该问题呢？
