### ISSUE TITLE
pods are created per Leadership status check

### ISSUE THREAD

**Issue by FunTK** [spring-cloud/spring-cloud-kubernetes#1671]
Hi 

Currently default of `spring.cloud.kubernetes.leader.update-period` property is 60s

So when leader-related actions are performed, pods are running and terminating seem to be repeated over and over again per 60s like the code in url below
pod running, old pod is terminating, new pod is creating > new pod is running, current pod is terminating, another new pod is created
**https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/leader/LeaderInitiator.java#L65-L67**

Can't the leader be updated among the currently working pods without the repeating process(creating and terminating)?

------------------------------------------------------------------------------------------------------------------------------------------

One more thing 
how to set `spring.cloud.kubernetes.leader.update-period` in application.yaml?

https://docs.spring.io/spring-cloud/docs/current/reference/html/configprops.html 
I checked the page, but default value is 60000ms for spring.cloud.kubernetes.leader.update-period property.
can I set it as below? 
`spring.cloud.kubernetes.leader.update-period : 60s `
or
`spring.cloud.kubernetes.leader.update-period : 3600 `

I added code as below but the 'update-period' seems not working
```
spring:
   ....
  cloud:
    kubernetes:
      leader:
        enabled: true
        role: "batch-role"
        config-map-name: "kdms-device-query-service"
        namespace: "${DQS_NAMESPACE:default}"
        update-period: 3600000
```

**Comment by ryanjbaxter** [comment]
Are you implying that leader election is causing the pod to restart every 60 seconds?

**Comment by ryanjbaxter** [comment]
UpdatePeriod is a `Duration` so you should be able to set it using `120s`

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/leader/LeaderProperties.java#L63

**Comment by FunTK** [comment]
I put 3600s to update-period field as below

```
spring:
   ....
  cloud:
    kubernetes:
      leader:
        enabled: true
        role: "batch-role"
        config-map-name: "kdms-device-query-service"
        namespace: "${DQS_NAMESPACE:default}"
        update-period: 3600s
```

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/leader/LeaderInitiator.java#L65-L66

So I think the update() in leaderController is executed per 3600s  (because update-period is set to 3600s)

But that function happens very often.

https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-leader/src/main/java/org/springframework/cloud/kubernetes/fabric8/leader/Fabric8LeadershipController.java#L57
