### ISSUE TITLE
Configuring spring boot kubernetes watcher to use actuator/shutdown endpoint doesn’t work as expected

### ISSUE THREAD

**Issue by MeravYa** [spring-cloud/spring-cloud-kubernetes#1772]
Version: 3.1.3

I’m using the basic spring boot kubernetes config watcher image. When trying to set the reload strategy to shutdown - the spring boot kubernetes watcher is still using the /actuator/refresh endpoint.
I was adding this environment var to the watcher deployment:
spring.cloud.kubernetes.reload.strategy: shutdown

But when trying to change the config map, the application is only refreshed and not shuts down.

**Comment by ryanjbaxter** [comment]
Agree I can take a look at this one

**Comment by MeravYa** [comment]
@wind57 that could be great since refresh is insufficient for my use case, the environment is not reloaded as expected. 
Meanwhile - is there any reference where I can understand what I am doing wrong? I am setting all spring properties as environment vars in my application deployment, which is obviously not reloaded upon refresh. 
Thanks a lot for your quick response!

**Comment by MeravYa** [comment]
Ok sure I will try to show a sample:
This is how my application deployment looks like:

`apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample_app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
         env:
            - name : SOME_PROPERTY
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SOME_PROPERTY`

The config map will look like this:

`apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  labels:
    spring.cloud.kubernetes.config: "true"
  annotations:
    spring.cloud.kubernetes.configmap.apps: sample-app
data:
  SOME_PROPERTY: some_value`


The property is initialized using 
`@Configuration
@ConfigurationProperties`

Now, when trying to reload the property either by hitting the /refresh manually, or by using the watcher - the property is not reloading. Only a complete shutdown will do the reload.

Thanks

**Comment by MeravYa** [comment]
Ok sure I will try to show a sample:
This is how my application deployment looks like:

```
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: sample-app 
  labels: app: sample-app 
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name:  sample-app
          image: "some-image:some-tag"
          ports:
            - containerPort: 8888
              protocol: TCP
          env:
            - name: SOME_PROPERTY
              valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: SOME_PROPERTY
``` 

The config map will look like this:

```
apiVersion: v1 
kind: ConfigMap
metadata: 
  name: configmap 
  labels: 
    spring.cloud.kubernetes.config: "true" 
  annotations: 
    spring.cloud.kubernetes.configmap.apps: sample-app 
data: 
  SOME_PROPERTY: some_value
``` 

The property is initialized using
@Configuration 
@ConfigurationProperties

Now, when trying to reload the property either by hitting the /refresh manually, or by using the watcher - the property is not reloading. Only a complete shutdown will do the reload.

Thanks
