### ISSUE TITLE
Label selector instead of list of services

### ISSUE THREAD

**Issue by fnarvaez-applydigital** [spring-cloud/spring-cloud-kubernetes#1816]
**Is your feature request related to a problem? Please describe.**
Currently, the configuration uses a list of service names to specify which services needs to be notified when a configmap change. This approach requires manual updates whenever services are added, removed, or renamed, leading to potential maintenance overhead and errors.

**Describe the solution you'd like**
Modify the configuration to use label selectors instead of a list of service names. This can be done by specifying the desired labels in a selector field. For example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-config
  namespace: your-namespace
  annotations:
    spring.cloud.kubernetes.configmap.labelsSelector: |
      { labelA: "a", labelB: "b" }
data:
  ....
```

Using label selectors instead of explicitly listing service names can make it more flexible and scalable. This approach allow to dynamically select services based on their labels, which can be particularly useful in environments where services are frequently added, removed, or changed.
