### ISSUE TITLE
KubernetesDiscoveryClientAutoConfiguration instantiated when spring.cloud.kubernetes.enabled is false

### ISSUE THREAD

**Issue by aantono** [spring-cloud/spring-cloud-kubernetes#183]
KubernetesDiscoveryClientAutoConfiguration instantiated when `spring.cloud.kubernetes.enabled` property is set to `false`

This causes startup exception:

```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'discoveryClient' defined in class path resource [org/springframework/cloud/kubernetes/discovery/KubernetesDiscoveryClientAutoConfiguration.class]: Unsatisfied dependency expressed through method 'discoveryClient' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.fabric8.kubernetes.client.KubernetesClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

`KubernetesDiscoveryClientAutoConfiguration` should be also annotated with `@ConditionalOnProperty(value = "spring.cloud.kubernetes.enabled", matchIfMissing = true)` similar to `KubernetesAutoConfiguration` class.

**Comment by ryandawsonuk** [comment]
I've realised I raised a duplicate in https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/issues/188 so I've closed that

**Comment by sta-szek** [comment]
I don't know if I created duplicate? https://github.com/spring-cloud-incubator/spring-cloud-kubernetes/issues/196

**Comment by geoand** [comment]
@sta-szek Your issue is most likely a duplicate.

I will create a PR to address these issues

**Comment by geoand** [comment]
I just saw that #189 should take care of the issue

**Comment by aantono** [comment]
I don't think #189 will take care of this issue as it only checks for the `discovery` property to be enabled, so if one decides to globally disable `spring.cloud.kubernetes.enabled=false`, it will not have the desired effect on the condition added as part of #189

**Comment by geoand** [comment]
@aantono Perhaps then you can comment in the PR and make sure the author knows it? FWIW, I agree with you about needing to add an extra conditional on `spring.cloud.kubernetes.enabled`

**Comment by matiasah** [comment]
I'm using Spring Cloud Consul discovery on a dev profile and I'm having this exact same issue with Spring Cloud kubernetes.
```yaml
spring:  
  application:
    name: user-auth-service
---
spring:
  profiles: prod
  cloud:
    # Kubernetes
    kubernetes:
      enabled: true
    # Consul
    consul:
      enabled: false
    # Vault
    vault:
      authentication: KUBERNETES
      kubernetes:
        role: user-auth-service
      uri: http://vault.vault.svc.cluster.local:8200
---
spring:
  profiles: dev
  cloud:
    # Kubernetes
    kubernetes:
      enabled: false
      discovery:
        enabled: false
    # Consul
    consul:
      host: consul
      port: 8500
      enabled: true
      discovery:
        enabled: true
        instance-id: ${spring.application.name}:${spring.cloud.client.hostname}
        health-check-url: http://${spring.cloud.client.hostname}:8080/actuator/health
    # Vault
    vault:
      authentication: APPROLE
      uri: http://vault:8200
```
