### ISSUE TITLE
spring.config.import reading incorrect data when profiles are involved

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#1874]
Sorry upfront for the bad title, I could not figure out of a better one. 

It looks a bit related to [this issue](https://github.com/spring-cloud/spring-cloud-config/issues/2392) what I am going to describe next. 

If I have an `application.yaml`:

```
spring:
  cloud:
    kubernetes:
      config:
        enable-api: true
        sources:
          - namespace: default
            name: sample-configmap
```

and `application-dev.yaml`:

```
spring:
  cloud:
    kubernetes:
      config:
        enable-api: true
        sources:
          - namespace: default
            name: sample-configmap-dev
```

and I do two things 1) use `spring.cloud.import:kubernetes` 2) make `dev` an active profile.

In this case, our code will bind `sample-configmap` as the name. This was un-expected for me, as I really thought it should be `sample-configmap-dev`. The logic happens in `KubernetesConfigDataLocationResolver::resolveProfileSpecific` and, although that method accepts a `Profiles profiles` I did not find any way to use that `profile` when binding (using `Binder`) happens.

Looking around a little and reading some of the threads on the matter (though I vaguely understand the idea), it seems that this is normal? And there is not much we can do, but suggest to users in such cases to use the bootstrap?

Thank you.

**Comment by ryanjbaxter** [comment]
> I did not find any way to use that profile when binding (using Binder) happens.

Can you elaborate on what you mean by this?  I am not sure I understand what you mean by using the profile when binding happens.

**Comment by ryanjbaxter** [comment]
So I am trying to wrap my head around this so sorry if I am asking what seems like obvious questions...

application.yaml and application-dev.yaml are not in a configmap they are configuration files in the application itself?

If that is a correct assumption, you are activating the profile `dev` but when we call `binder.bindOrCreate("spring.cloud.kubernetes.config", ConfigMapConfigProperties.class);` the value of `spring.cloud.kubernetes.config.sources[0].name` is `sample-configmap` instead of `sample-configmap-dev`?

**Comment by ryanjbaxter** [comment]
This might be a long shot but I noticed we are not using a `BindHandler` like we are in Spring Cloud Config,
https://github.com/spring-cloud/spring-cloud-config/blob/175472746dc9100ec27daddf88aeb937597a666f/spring-cloud-config-client/src/main/java/org/springframework/cloud/config/client/ConfigServerConfigDataLocationResolver.java#L114-L121

We might try doing that and seeing if it make a difference.

This code is very complicated from the Boot side and its always a pain to figure out how it works.  I do know that when profiles get activated the local configuration files should be loaded and be active in the context before Boot tries to resolve anything from `spring.config.import` so the configuration from `application-dev.yaml` should take precedence when we create `ConfigMapConfigProperties`.

**Comment by ryanjbaxter** [comment]
It is going to take me more time to dive into this some more, but I found two approaches that appear to make this work:

You can add a separate document to `application.yaml` with 
```
---
spring:
  config:
    activate:
      on-profile: dev
```

or you can add `spring.config.import: "kubernetes:"` to `application-dev.yaml`
