### ISSUE TITLE
Secrets not evaluated

### ISSUE THREAD

**Issue by davgia** [spring-cloud/spring-cloud-kubernetes#1915]
**Describe the bug**
Kubernetes: v1.31.3
Container: amazoncorretto:21-alpine
Spring boot: v3.4.5
Spring cloud: v2024.0.1

I have updated one of my microservices to the latest spring boot/cloud version. I've deployed it in my Kubernetes cluster and at startup the service crashes. The crash in an applicative exception I throw when I do not find a specific value in the service configuration. It was working fine in the previous release (spring boot 3.1.0, spring cloud 2022.0.2).

In the Kubernetes cluster, in the same namespace as the Deployment, there is Secret I mount in the Pod. I then declare the environment variable SPRING_CLOUD_KUBERNETES_SECRETS_PATHS to make Spring read the mounted secret. It appears that the secret is NOT read.

Those are my manifest stripped down at the bare minimum:

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  namespace: development
spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_PATHS
          value: /etc/secrets/demo-service
        volumeMounts:
        - mountPath: /etc/secrets/demo-service
          name: demo-service-volume
          readOnly: true
      volumes:
      - name: demo-service-volume
        secret:
          secretName: demo-service
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: demo-service
  namespace: development
stringData:
  required-secret: "my-secret"
```

I declare the following dependencies in my pom.xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<dependencies>
		<!-- Kubernetes integration -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-kubernetes-fabric8</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-kubernetes-fabric8-loadbalancer</artifactId>
		</dependency>
    </dependencies>
</project>
```
