### ISSUE TITLE
Dynamic configuration of property source using label rather than names

### ISSUE THREAD

**Issue by AssafKatz3** [spring-cloud/spring-cloud-kubernetes#214]
I suggest taking futher step from [ConfigMap PropertySource](https://github.com/spring-cloud-incubator/spring-cloud-kubernetes#configmap-propertysource) and allow support controller about kubernetes.
Suggest configuration is:
```
spring:
  application:
    name: cloud-k8s-app	
  cloud:
    kubernetes:
      config:
        namespace: default-namespace
        sources:
         # Spring Cloud Kubernetes will lookup a ConfigMap labeled config-label with value c1 in namespace default-namespace 
         - label: config-label
           value: c1
         # Spring Cloud Kubernetes will lookup a ConfigMap labeled config-label2 with value c3 in namespace in namespace n3
         - namespace: n3
           label: config-label2
           value: c3
```

1. Each add/patch/remove of config maps with this these ConfigMap will change the configuration.
2. The ConfigMap will be used same as they directly wrote as part of spring configuration
