### ISSUE TITLE
Cannot load multiple mounted configmap with multiple application.yaml

### ISSUE THREAD

**Issue by au-hao** [spring-cloud/spring-cloud-kubernetes#230]
I would like to use multiple mounted config maps and according to the source code `KubernetesPropertySource.java`, same key `application.yaml` will be overwritten in the result `HashMap` which causes that multiple config maps cannot be loaded at the same time and only the last mounted configmap that has the same key can be loaded successfully.  Need a help since I am not sure if this is the design or it is a bug. Also I tried consuming configmap from API which works.

Configuration files:
```yaml
# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-spring-1
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |-
    deployment:
      type: cloud
      name: beta
```
```yaml
# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-spring-2
  namespace: {{ .Release.Namespace }}
data:
  application.yaml: |-
{{ .Files.Get "application.yaml" | indent 4 }}
    ---
    spring.profiles: {{ .Values.springProfile }}
{{ .Files.Get (printf "application-%s.yaml" .Values.springProfile) | indent 4 }}
```
```yaml
# values.yaml
springProperties:
  spring:
    cloud:
      kubernetes:
        config:
          enableApi: false
          paths:
            - "/home/configmaps"
        reload:
          enabled: true
```
