### ISSUE TITLE
"kubernetes" profile is active when running inside kubernetes, but profile is not selected/active within application.yaml

### ISSUE THREAD

**Issue by magnusheino** [spring-cloud/spring-cloud-kubernetes#276]
Starting a pod within kubernetes will activate the "kubernetes" profile (it prints in the startup log that it is active), but "kubernetes" profiles within application.yaml aren't selected. Is the "kubernetes" profile activated after application.yaml is parsed?

**Comment by geoand** [comment]
Does [this](https://github.com/spring-cloud/spring-cloud-kubernetes#kubernetes-profile-autoconfiguration) cover your questions?

**Comment by magnusheino** [comment]
Well, no. Spring says that "kubernetes" profile is active when starting, but the "kuberenetes" profile in application.yaml isn't activated. This config would start the server on 8081, not 8080:

```
---
server:
  port: 8081
management:
  port: 8091`
---
spring:
  profiles: kubernetes
server:
  port: 8080
management:
  port: 8090
```
