### ISSUE TITLE
ConfigMap not picked up by Spring Boot

### ISSUE THREAD

**Issue by mribeiro** [spring-cloud/spring-cloud-kubernetes#304]
This will be a long post, excuse me if this does not belong here. I'm looking for some help sorting this out. I don't mind looking at logs and debugging the app somehow, problem is that now I feel stuck and have no idea where to turn to.
Here's my goal:

1. Load a configuration from config map
2. Output that config in a resource `/info`
3. Change the config map
4. See the new value when accessing resource `/info`

I'm stuck in point 2.
For some reason I don't see the Spring Boot app picking the configurations in an existing configmap. 
I'm using Spring Cloud Kubernetes 1.0.0.RC2 (also tried with '+' version selector and fetched .0.3.0 RELEASE and problem remains):
```
repositories {
     mavenCentral()
     maven { url "https://repo.spring.io/milestone" }
}
dependencies {
    compile("org.springframework.cloud:spring-cloud-starter-kubernetes:1.0.0.RC2")
}
```
I have a class named `ResInfoConf` which loads the config `info.text`:
```
@Configuration
@ConfigurationProperties(prefix = "info")
public class ResInfoConf {
    private String text = "default info";
    // getters and setters below
```
Which is returned in a simple rest interface:
```
@RestController
@RequestMapping("/info")
public class Info {
    @Autowired
    private ResInfoConf resInfoConf;
    @RequestMapping(method = RequestMethod.GET)
    public HttpEntity<String> get() {
        return ResponseEntity.ok(resInfoConf.getText());
    } 
}
```

Every time I access the `/info` resource I always get the output as `default info`.

I have this ConfigMap:
```
apiVersion: v1
data:
  application.properties: info.text=1This is an info from k8
kind: ConfigMap
metadata:
  creationTimestamp: 2018-12-27T14:07:29Z
  name: i18n
  namespace: default
  resourceVersion: "30569"
  selfLink: /api/v1/namespaces/default/configmaps/i18n
  uid: bee7dd59-09e0-11e9-9c76-08002719185c
```

And the following deployment (cut off irrelevant parts):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i18n
  labels:
    app: i18n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i18n
  template:
    metadata:
      labels:
        app: i18n
    spec:
      serviceAccountName: i18n-spring-k8
      containers:
      - name: i18n
        image: aribeiro/i18n-spring
        imagePullPolicy: Never
        env:
          - name: JAVA_OPTS
            value: -Dserver.port=8080 -Xmx256M -Xms128M -Dlogging.level.root=DEBUG
        ports:
          - containerPort: 8080
      volumes:
        - name: i18n
          configMap:
            # Provide the name of the ConfigMap containing the files you want
            # to add to the container
            name: i18n
```

So, all names are set to i18n so there are no other names in the mix. The `serviceAccountName: i18n-spring-k8` is also valid as I created it with all permissions for everything.

Last but no least, the `application.properties` also bundle some info that should help Spring Cloud K8 finding the map:

```
spring.application.name=i18n
spring.cloud.kubernetes.config.name=i18n
spring.cloud.kubernetes.config.enabled=true
spring.cloud.kubernetes.config.namespace=default
spring.cloud.kubernetes.reload.enabled=true
spring.cloud.kubernetes.reload.monitoring-config-maps=true
spring.cloud.kubernetes.reload.strategy=refresh
spring.cloud.kubernetes.reload.mode=event
```
I also tried putting said properties in the bootstrap.properties file but still no luck.

As said, all names set to i18n so there are no mistakes.

In the logs I think these are the only relevant ones:
```
io.fabric8.kubernetes.client.Config      : Trying to configure client from Kubernetes config...
io.fabric8.kubernetes.client.Config      : Did not find Kubernetes config at: [/root/.kube/config]. Ignoring.
io.fabric8.kubernetes.client.Config      : Trying to configure client from service account...
io.fabric8.kubernetes.client.Config      : Found service account host and port: 10.96.0.1:443
io.fabric8.kubernetes.client.Config      : Found service account ca cert at: [/var/run/secrets/kubernetes.io/serviceaccount/ca.crt].
io.fabric8.kubernetes.client.Config      : Found service account token at: [/var/run/secrets/kubernetes.io/serviceaccount/token].
io.fabric8.kubernetes.client.Config      : Trying to configure client namespace from Kubernetes service account namespace path...
io.fabric8.kubernetes.client.Config      : Found service account namespace at: [/var/run/secrets/kubernetes.io/serviceaccount/namespace].
k.p.KubernetesProfileApplicationListener : 'kubernetes' already in list of active profiles
org.aribeiro.i18n.I18nApplication        : The following profiles are active: kubernetes
o.s.boot.SpringApplication               : Loading source class org.aribeiro.i18n.I18nApplication
o.s.b.c.c.ConfigFileApplicationListener  : Loaded config file 'file:/app/application.properties' (classpath:/application.properties)
ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@26a4842b
o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
o.s.b.f.s.DefaultListableBeanFactory     : Creating shared instance of singleton bean 'org.springframework.boot.autoconfigure.internalCachingMetadataReaderFactory'
o.s.c.a.ClassPathBeanDefinitionScanner   : Identified candidate component class: file [/app/org/aribeiro/i18n/configs/ResInfoConf.class]
```
The content of the file `/var/run/secrets/kubernetes.io/serviceaccount/namespace` in the node is literally `default` -- which is where I have both the pod and config map created (the /app/application.properties is the file containing the configs of spring cloud k8 shown above).
The class which is `@Autowired` and is annotated with `@Configuration` is `/app/org/aribeiro/i18n/configs/ResInfoConf.class` so it seems to be found as a candidate for Singleton.

EDIT: I created a minimum example and posted on stack overflow. Included a project, K8 yaml files and Dockerfile for quick run and test. If you have the chance check it at https://stackoverflow.com/questions/53960467/spring-cloud-kubernetes-spring-boot-not-reading-config-map
