### ISSUE TITLE
Lookup ConfigMap based on profile

### ISSUE THREAD

**Issue by mribeiro** [spring-cloud/spring-cloud-kubernetes#305]
I have a generous file of configurations for my app and so it makes it simpler to create configmap using `kubectl create configmap --from-file` .
We have our configs in the application.properties and the rest is loaded based on the profile (application-<profile>.properties).

Now, it seems that this is only supported if there's a single key containing a file. For instance:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: demo
data:
  application.yml: |-
    bean:
      message: this is from default profile k8
    ---
    spring:
      profiles: kubernetes
    bean:
      message: loaded profile is kubernetes. hi!
```

What if I have the following (switching to properties as this is our preferred approach)?

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: demo
data:
  application.properties: |-
    bean.message=this is from default profile k8
  application-kubernetes.properties: |-
    bean.message=loaded profile is kubernetes. hi!
```

I don't see the app picking up the latest definition of `bean.message`. 

Another solution for me would be using `spring.cloud.kubernetes.config.sources`. Is it possible to indicate the ConfigMap `demo` must be loaded by default and, for instance, a configmap `demo-<profile>` depending on the profile?

Main goal is not having all configs in a single file.

Thanks
