### ISSUE TITLE
Enable binding of secrets to other prefixes

### ISSUE THREAD

**Issue by FWiesner** [spring-cloud/spring-cloud-kubernetes#355]
Say you have a standard secret that is shared across multiple applications:
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: my-secret
type: Opaque
data:
  secret1: VGVzdCAxMjM=
  secret2: VGVzdCAzNDU=
```
the keys of these secrets are not prefixed and as they would be shared, you might not want them prefixed (or can't if you're out of control of them). You can of course map them into your application, with a no-prefix configuration properties class. But, you might want to bind them to framework-defined configuration properties instead, like `spring.mail.properties.mail.smtp.proxy.password`. This currently is not possible out of the box, it seems
