### ISSUE TITLE
Service list does not refresh in Spring Cloud Gateway

### ISSUE THREAD

**Issue by vxavictor513** [spring-cloud/spring-cloud-kubernetes#384]
I'm using Spring Cloud Gateway Discovery + Spring Cloud Kubernetes.
```
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          predicates:
            - name: Path
              args[pattern]: "'/api/'+serviceId+'/**'"
          filters:
            - name: Hystrix
              args[name]: serviceId
            - name: RewritePath
              args[regexp]: "'/api/' + serviceId + '/(?<remaining>.*)'"
              args[replacement]: "'/${remaining}'"
```

The routing works fine for any services available upon Spring Cloud Gateway's startup, but the gateway is unable to detect any new services registered to Kubernetes afterwards.

Tried enabling `KubernetesCatalogWatch` but it doesn't help.
```
spring.cloud.kubernetes.discovery.catalog-services-watch.enabled=true
spring.cloud.kubernetes.discovery.catalog-services-watch.delay=5000
```

Did I miss out anything here?
