### ISSUE TITLE
How to fetch multiple secrets from multiple labels

### ISSUE THREAD

**Issue by raksit31667** [spring-cloud/spring-cloud-kubernetes#389]
# Context
I would like to fetch secrets for PostgreSQL and Redis which already deployed with different labels. According to the documentation, I can configure `bootstrap.yaml` as below:

```yaml
spring:
  application:
    name: my-application
  main:
    allow-bean-definition-overriding: true
  cloud:
    kubernetes:
      enabled: true
      reload:
        enabled: true
        monitoring-secrets: true
      secrets:
        name: credential
        enable-api: true
        labels:
          db: postgres
          redis: redis
```

# Expected behavior
The application should fetch secrets from PostgreSQL and Redis successfully.

# Current behavior
The application cannot fetch both secrets, it seems to me that it can only accept one label.
This means it works fine if I have only `db` label.

# Environment
- Spring Boot 2.1.0
- OpenShift 3.9
-  Spring Cloud Starter Kubernetes Config 0.3.0
