### ISSUE TITLE
Setting Spring configuration profile 

### ISSUE THREAD

**Issue by Alos** [spring-cloud/spring-cloud-kubernetes#403]
I've been trying to use the ConfigMaps with profiles but I've been unable to change the profile of my running application. 

I've added the following to my deployment.yaml:

```YAML
 env:
          - name: JAVA_OPTIONS
            value: -Dspring.profiles.active=development
```

No matter that I do when the application boots up in K8s it always has the `kubernetes` profile:
```
1 --- [ main] com.example.hello.HelloApplication : The following profiles are active: kubernetes
```

Am I missing something? Here is the full deployment.yaml:

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
  namespace: aNamespace
spec:
  selector:
    matchLabels:
      app: hello-service
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/path"
    spec:
      containers:
      - name: hello-service
        image: gcr.io/some-project/hello-service
        ports:
          - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 40
          httpGet:
            port: 8081
            path: /actuator/health
            httpHeaders:
              - name: x-b3-sampled
                value: "0"
        readinessProbe:
          initialDelaySeconds: 50
          httpGet:
            port: 8081
            path: /actuator/health
        env:
          - name: JAVA_OPTIONS
            value: -Dspring.profiles.active=development
```
