### ISSUE TITLE
Enable DiscoveryClient from all namespaces based on property opt in

### ISSUE THREAD

**Issue by Incarnation-p-lee** [spring-cloud/spring-cloud-kubernetes#428]
As we know, the package
```pom
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes</artifactId>
</dependency>
```
will discovery all services from k8s, and we can configure the namespace from property
```
spring:
  cloud:
    kuberenetes:
      client:
        namespace: ${my-namespace}
```

But how can I discovery services from all namespace ?
