### ISSUE TITLE
Replace `cluster-reader` with custom role/rolebinding

### ISSUE THREAD

**Issue by deveth0** [spring-cloud/spring-cloud-kubernetes#439]
Hi all,

The "official" Readme recommends to add the default user to the cluster reader role to afet the required permissions for pod, configmap etc lookup.
As far as I can see, this might be OK for development, but as soon as more than one projects runs in the same cluster, this prevents any isolation and might bring security issues. 
Therefor I think that it would be helpful to remove this recommendation (or at least give a strong warning) and add a new role which brings the required permissions. This role can then be bound to the default user adding an (optional) namespace.
Also it would be easy to customize the resources so that you can e.g. remove secrets if you have no need for them.
What do you think? 

````
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: YOUR-NAME-SPACE
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: YOUR-NAME-SPACE
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
````
