### ISSUE TITLE
The problem occurs when you have two or more namespaces, where the service name is the same

### ISSUE THREAD

**Issue by claitonp** [spring-cloud/spring-cloud-kubernetes#473]
The problem occurs when you have two or more namespaces, where the service name is the same.
Example: service 'price' is in namespaces ns1 and ns2 in the same cluster kubernetes.

xxx-service.yaml
-------------
```
metadata:
   namespace: ns1
   name: price
   labels:
       app: price
       group.department: dept1
```

yyy-service.yaml
-----------------
```
metadata:
  namespace: ns2
  name: price
  labels:
      app: price
      group.department: dept2
	  
```
app-discovery.yaml
------------	  
```
spring:
  cloud:
    kubernetes:
	discovery:
	  service-labels:
	  - group.department: dept1
```
In this case, the current code returns the endpoints of both namespaces, which is not expected.
To resolve this issue you have to apply the service-labels filter, **.withLabels(serviceLabels).**

spring-cloud-kubernetes, version:1.0.4.BUILD-SNAPSHOT	

```
package org.springframework.cloud.kubernetes.discovery;
public class KubernetesDiscoveryClient implements DiscoveryClient {
  ...
	@Override
	public List<ServiceInstance> getInstances(String serviceId) {
		...
		// bug
		// List<Endpoints> endpointsList = this.properties.isAllNamespaces()
		//	? this.client.endpoints().inAnyNamespace().withField("metadata.name", serviceId).list().getItems()
		//	: Collections.singletonList(this.client.endpoints().withName(serviceId).get());

		//adjusted
		Map<String, String> serviceLabels = properties.getServiceLabels();
		List<Endpoints> endpointsList = properties.isAllNamespaces() ?
				client.endpoints().inAnyNamespace().withField("metadata.name", serviceId).withLabels(serviceLabels).list().getItems()
				: Collections.singletonList(client.endpoints().withName(serviceId).get());
	}			
}
```

**Comment by spencergibb** [comment]
Please say what is happening. "Does not work correctly" isn't helpful at all.

**Comment by claitonp** [comment]
Hi,

When using serviceLabels, it is not filtering correctly:
```
  spring:
    cloud:
      kubernetes:
          discovery:
             service-labels:
```
To work properly, you must add: .withLabels(serviceLabels)

**Comment by claitonp** [comment]
In the class KubernetesDiscoveryClient.java , method getInstance(String serviceId).
To work properly you must add the code in bold.

**Map<String, String> serviceLabels = properties.getServiceLabels();**
		List<Endpoints> endpointsList = properties.isAllNamespaces() ?
				client.endpoints().inAnyNamespace().withField("metadata.name", serviceId)**.withLabels(serviceLabels)**.list().getItems()
				: Collections.singletonList(client.endpoints().withName(serviceId).get());
	}

**Comment by claitonp** [comment]
Hello, review the beginning of the question again, I made an edit to improve the situation that is occurring.

Thanks.

**Comment by m-kay** [comment]
I think there is not only a problem with the serivce label filter but more a general problem when `spring.cloud.kubernetes.discovery.all-namespaces` is set to true. Since in Kubernetes you can access the services by <namespace>.<service-name> this should also be reflected in the discovery client. I'm facing the problem in Spring Boot Admin where services with the same name but in different namespaces are shown as one service.

**Comment by claitonp** [comment]
To resolve this situation I overwrite the SBA and the Sprign Cloug Gateway, add .withLabels(serviceLabels)

```
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(name = "spring.cloud.kubernetes.discovery.enabled", matchIfMissing = true)
    public KubernetesDiscoveryClient kubernetesDiscoveryClient(KubernetesClient client,
            KubernetesDiscoveryProperties properties,
            KubernetesClientServicesFunction kubernetesClientServicesFunction) {
    	
        KubernetesDiscoveryClient result = new KubernetesDiscoveryClient(client, properties, kubernetesClientServicesFunction) {          

            @Override
            public List<ServiceInstance> getInstances(String serviceId) {

                log.debug("KubernetesClient: {}", client);
                Assert.notNull(serviceId, "[Assertion failed] - the object argument must not be null");

                Map<String, String> serviceLabels = properties.getServiceLabels();
                List<Endpoints> endpointsList = properties.isAllNamespaces() ? 
                        client.endpoints().inAnyNamespace().withField("metadata.name", serviceId).withLabels(serviceLabels).list().getItems()
                        : Collections.singletonList(client.endpoints().withName(serviceId).get());
            ....
```

application-dev.yaml SBA:
```
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
        all-namespaces: true
        service-labels:
          environment: "dev"
```

Spring Cloud Gateway:

```
gateway
  discovery:
    locator:
      enabled: true
        lower-case-service-id: true
        include-expression: true
        url-expression: "'http://' + serviceId + '.' + endpointAddress.targetRef.namespace + ':' + port" 

kubernetes:
  enabled: true
  discovery:
     enabled: true
     all-namespaces: true
     service-labels:
       environment: "dev" 

```
