### ISSUE TITLE
kubernetes.client.namespace not honored when using ConfigMap PropertySource and DefaultKubernetesClient

### ISSUE THREAD

**Issue by HJK181** [spring-cloud/spring-cloud-kubernetes#483]
Given a Service `A1` in namespace `A` and a POD `B1` running in namespace `B` with the following ConfigMap for Pod B1:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: B1
data:
  application.yml: |-
    server:
      port: 8092
    spring:
      profiles: kubernetes
      cloud:
        kubernetes:
          client:
            namespace: A
          discovery:
            enabled: true
    A1:
      ribbon:
        NIWSServerListClassName: org.springframework.cloud.kubernetes.ribbon.KubernetesServerList
        KubernetesNamespace: A
        PortName: https
```

The `DefaultKubernetesClient` uses the namespace where POD B1's ConfigMap is applied instead of the value from `kubernetes.client.namespace` when asked to get all services from `KubernetesDiscoveryClient#getInstances`. The problem is that `ConfigMapConfigProperties#determineSources` set's the namespace for the client to the namespace the ConfigMap is deployed to.

Using the same configuration above with `spring-cloud-configuration` where the `application.yml` is served from a GIT repo work perfectly fine.

**Comment by HJK181** [comment]
Update: Updated my bootrap.yml of Pod B1 the following way:
```
 cloud:
    kubernetes:
      reload:
        enabled: true
      config: 
        name: B1
        namespace: A
```
And placed the ConfMap in namespace `A`. This does not resolve to problem, so I debugged a bit deeper and found that `io.fabric8.kubernetes.client.Config.tryNamespaceFromPath(Config)` is setting the namespace used in the client. Seams that the value from `application.yml` placed in the ConfigMap gets ignored ...
