### ISSUE TITLE
Using ExternalName service type with KubernetesDiscoveryClient

### ISSUE THREAD

**Issue by ArtyomGabeev** [spring-cloud/spring-cloud-kubernetes#489]
Imagine you have a setup when services running in K8S need to access services running outside.

I want to create an ExternalName service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: prod
spec:
  type: ExternalName
  externalName: my.service.example.com
```
After that I should be able to resolve service call http://my-service/doCall into http://my.service.example.com/doCall

So instead of relying only on endpoints in KubernetesDiscoveryClient, check if service type is ExternalName, then return single service instance with hostname: `my.service.example.com`.

Does it make sense to contribute this enhancement?
