### ISSUE TITLE
Environment variable does not override value in configmap

### ISSUE THREAD

**Issue by sloppycoder** [spring-cloud/spring-cloud-kubernetes#498]
**Describe the bug**
When running Spring Boot application outside K8S, the environment variable value always overrides what is in application.yml. However, with spring-cloud-kubernetes-config, the value defined in configmap always takes precedent.

**Sample**
My application.yml
```
spring:
  datasource:
      url: jdbc:h2:mem:dummydb
      username: none
      password: none
```
My K8S manifest
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: web
        image: minikube.local:5000/dev/sample-api-svc
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_PASSWORD
            value: from_k8s_manifest_not_env
```
In my application the configuration always get the value from configmap, 'none', instead of the value from manifest.

**Comment by sloppycoder** [comment]
I created a test repo to demostrate the issue

https://github.com/sloppycoder/boot-k8s-configmap-test

**Comment by spencergibb** [comment]
This is by design. There's a property in commons that will allow the opposite. Will look for it when in laptop

**Comment by sloppycoder** [comment]
thanks for the tip. Adding the following to application.yml solved my problem
```
cloud:
    config:
      allow--override: true
      override-system-properties: false
```
[spring cloud config docs](https://cloud.spring.io/spring-cloud-static/spring-cloud.html) has more details.
