### ISSUE TITLE
Allow activeProfile not to be appended

### ISSUE THREAD

**Issue by hannes-angst** [spring-cloud/spring-cloud-kubernetes#508]
When configuring the configMap, the activate Profile is appended to the name

```
spring:
  cloud:
    kubernetes:
      enabled: true
      client:
        namespace: default
      reload:
        enabled: true
        monitoring-config-maps: true
        monitoring-secrets: false
        mode: event
        strategy: refresh
      config:
        enable-api: true
        sources:
          - namespace: default
            name: feature-toggles
```

results in `https://172.20.0.1/api/v1/namespaces/default/configmaps/feature-toggles-dev`, which active profile `dev`.

Cause is the line 
`String mapNameWithProfile = name + "-" + activeProfile;` 

from
`m2/repository/org/springframework/cloud/spring-cloud-kubernetes-config/1.1.1.RELEASE/spring-cloud-kubernetes-config-1.1.1.RELEASE-sources.jar!/org/springframework/cloud/kubernetes/config/ConfigMapPropertySource.java:102`

Please make the addition of the activate profile to the configMap an configuration property ("append-profile: true/false,  default: true).
