### ISSUE TITLE
Cant connect to API server to fetch details

### ISSUE THREAD

**Issue by ravening** [spring-cloud/spring-cloud-kubernetes#551]
**Describe the bug**
I deployed a sample Spring boot application on Kuberntes cluster using spring cloud kubernetes config library and I continuously see exceptions in the pod

```
10:17:48.034 [PollingServerListUpdater-0] WARN  c.n.l.PollingServerListUpdater - Failed one update cycle                                                   │
│ io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Endpoints]  with name: [travel-agency-service]  in namespace: [test]

Caused by: java.net.SocketTimeoutException: connect timed out
```

Im following the example mentioned [here](https://github.com/fabric8io/spring-cloud-kubernetes/tree/master/spring-cloud-kubernetes-examples/kubernetes-reload-example)

**Sample**
Below is my kubernetes yaml files

Config.yaml

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-service
data:
  application.yaml: |-
    bean.message=Testing reload ! Message from backend is: %s <br/> Services : %s
```

Deployment.yaml

```
kind: Service
apiVersion: v1
metadata:
  name: client-service
spec:
  selector:
    app: client-service
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30072
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
spec:
  selector:
      matchLabels:
        app: client-service
  replicas: 1
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service
          image: <dockerhub>/client-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
```
