### ISSUE TITLE
ribbon.mode SERVICE doesn't work

### ISSUE THREAD

**Issue by DmitryevichD** [spring-cloud/spring-cloud-kubernetes#552]
**Describe the bug**
I sets a ribbon property spring.cloud.kubernetes.ribbon.mode: SERVICE to my application.yml, but my client sends request by Pod IP address. After that I downloads this project and don't find KubernetesRibbonMode in the code. Also I don't find in the code  SERVICE and POD rules.  
I looked at examples from the documentation but I didn't find the use of these setting. 

Please, explain how it work or give a  link to the code with KubernetesRibbonMode 

springCloudVersion = 'Greenwich.SR2'
springBootVersion = '2.1.6.RELEASE'

Thanks.

**Sample**
```yaml
spring:
  profiles:
    active: dev
  application:
    name: otp
  cloud:
    kubernetes:
      ribbon:
        mode: SERVICE
```
