### ISSUE TITLE
Multiple binders not working with Spring-Cloud-Stream and Spring-Kubernetes only on Kubernetes

### ISSUE THREAD

**Issue by avpines** [spring-cloud/spring-cloud-kubernetes#553]
**Describe the bug**

I have Spring-Cloud-Stream Azure Service-Bus Binder application with uses multiple binders: 

```yaml
spring:
  application:
    name: my-application
  cloud:
    azure:
      servicebus:
        connection-string: CON_STRING_1
    stream:
      binders:
        second-binder:
          type: servicebus-queue
          default-candidate: false
          environment:
            spring:
              cloud:
                azure:
                  servicebus:
                    connection-string: CON_STRING_2
      bindings:
        first-destination:
          destination: first-binder-queue
        second-destination:
          destination: second-binder-queue
          binder: second-binder
      function:
        definition: my-function
```

When I am running the application locally it connects to both binders successfully.

```plain
...
Created queue client to connection string 'Endpoint=CON_STRING_1;EntityPath=first-binder-queue;'
...
Created queue client to connection string 'Endpoint=CON_STRING_2;EntityPath=second-binder-queue;'
...
```

When attempting to deploy the application Kubernetes however, the second binder doesn't work. I've moved the configuration to a ConfigMap:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  # same name as the application
  name: my-application
data:
  application.yaml: |-
    spring:
      application:
        name: my-application
      cloud:
        azure:
          servicebus:
            connection-string: CON_STRING_1
        stream:
          binders:
            second-binder:
              type: servicebus-queue
              default-candidate: false
              environment:
                spring:
                  cloud:
                    azure:
                      servicebus:
                        connection-string: CON_STRING_2
          bindings:
            first-destination:
              destination: first-binder-queue
            second-destination:
              destination: second-binder-queue
              binder: second-binder
      function:
        definition: my-function
```

I have the `spring-cloud-starter-kubernetes-config`, and the configuration is read from the config map, but the second binder is not being used, and the application attempts to connect to the second queue but in the **_first_ binder**

```plain
com.microsoft.azure.servicebus.primitives.MessagingEntityNotFoundException: The messaging entity 'CON_STRING_1/second-binder-queue' could not be found. To know more visit https://aka.ms/sbResourceMgrExceptions.
```

1. The application does take the first connection string and other properties from the config map - the property source works as described in the [Spring-Kubernetes documentation](https://cloud.spring.io/spring-cloud-static/spring-cloud-kubernetes/1.1.2.RELEASE/reference/html/#configmap-propertysource).
1. If I deploy the application without the config map and keep the `application.yaml` in the jar, **the application works as expected**.

To conclude:
1. Works locally as expected.
1. Works on Kubernetes with the information directly in the `application.yaml` file as expected.
1. Resolves the ConfigMap and takes configuration from it.

I understand that this issue has multiple components, and if you have any idea how I can investigate it further / provide you with more information I'll be happy to do so.

I have posted the issue as a [StackOverflow question](https://stackoverflow.com/questions/61559074/multiple-binders-not-working-with-spring-cloud-stream-and-spring-kubernetes-on-k) as well, in case it's another component and not Spring-Cloud-Kubernetes that has the issue. If something comes up there I will update it here.
