### ISSUE TITLE
issue on getting values from configmap in kubernetes when the name of the configmap is different from application one 

### ISSUE THREAD

**Issue by ziflea** [spring-cloud/spring-cloud-kubernetes#577]
I have implemented a XXXconfigmap.yaml where i have values needed on different microservices.

In application.properties of each microservice i have specified the key spring.cloud.kubernetes.config.name with the name of the configmap but it doesn't find it , when i do the configmap the same name as the microservice everything works fine.

This is the configmap yaml: 

apiVersion: v1 
kind: ConfigMap
metadata:
  name: XXXconfigmap
  namespace: testName
data:
 someData: "values"

in application.properties i have :
spring.cloud.kubernetes.config.namespace=testName
spring.cloud.kubernetes.config.name=XXXconfigmap

**Comment by Haybu** [comment]
is the app in namespace testName also ?

**Comment by ziflea** [comment]
yes also the app is in that namespace @Haybu

**Comment by Haybu** [comment]
I have it working just fine with spring boot 2.3.1.RELEASE and spring cloud Hoxton.SR6 and the configuration for a service like the one below (notice app name is different than the cm name):

```
spring:
  application:
    name: backend
  cloud:
    kubernetes:
      enabled: true
      config:
        enabled: true
        name: mybackend
```
