### ISSUE TITLE
Profile doesn't work on application.properties file but on equivalent yaml file

### ISSUE THREAD

**Issue by l0rem1psum** [spring-cloud/spring-cloud-kubernetes#600]
**Describe the bug**
I have a configmap with a `application.properties` file which has some custom values. It also makes use of different profiles. However, the value in the active profile is not read by the application. Switching to equivalent `application.yml` file works.

**Sample**
The original configmap with `application.properties` is as follows (truncated for brevity):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |-
    ....
    ---
    spring.profiles: staging
    verification.url.format: https://api.dev.url.com/verification?email=%s&token=%s
    ---
    spring.profiles: prod
    verification.url.format: https://api.url.com/verification?email=%s&token=%s
``` 
When I try to read `verification.url.format` in the `staging` profile, it gives me the string in `prod` profile. However, switching to the following configmap works:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.yml: |-
    ....
    ---
    spring:
      profiles: staging
    verification:
      url:
        format: https://api.dev.url.com/verification?email=%s&token=%s
    ---
    spring:
      profiles: prod
    verification:
      url:
        format: https://api.url.com/verification?email=%s&token=%s
``` 

Environment:
- Spring Boot 2.3.1.REALEASE
- Spring Cloud Kubernetes: 1.1.4.RELEASE
