### ISSUE TITLE
SecretsPropertySource - read secrets directly from a mounted volume

### ISSUE THREAD

**Issue by dkirrane** [spring-cloud/spring-cloud-kubernetes#632]
**Describe the bug**
Is there an example of howto use `spring.cloud.kubernetes.secrets.paths=/mnt/secrets` property to read secrets as files (mounted as a volume)? I cannot get it to work.

**Sample**

```
kind: Pod
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  labels:
    aadpodidbinding: pod-mi
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: foo
          mountPath: "/mnt/secrets"
          readOnly: true
  volumes:
    - name: foo
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: spc
```

I can see the secrets get mounted correctly:
```
kubectl -n default exec -it nginx -- bash
root@nginx:/# ls /mnt/secrets
service-one-secret
service-two-secret
```

BUT I cannot find a way to read them from the mount
The following does not work:
```
import lombok.Data;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.context.annotation.Configuration;

import java.util.HashMap;
import java.util.Map;

@Configuration
@ConfigurationProperties(prefix = "secrets")
@Data
public class ApplicationSecrets {

//    private String serviceOneSecret;
//    private String serviceTwoSecret;

//    private final List<String> secrets= new ArrayList<>();

    private final Map<String, Object> secrets = new HashMap();

}
```

I've also tried `@Value` but that does not work
```
    @Value("${service-one-secret}")
    private String serviceOneSecret;
```

application.yml
```
spring:
  application:
    name: secrets-demo
  cloud:
    kubernetes:
      secrets:
        enabled: true
        paths: /mnt/secrets
```

I'm using
```
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-kubernetes-config</artifactId>
			<version>1.1.6.RELEASE</version>
		</dependency>
```
