### ISSUE TITLE
IllegalArgumentException: Unable to find GatewayFilterFactory with name RequestRateLimiter

### ISSUE THREAD

**Issue by claitonp** [spring-cloud/spring-cloud-kubernetes#652]
Hi,

After migration of the Gateway the following error occurred in RequestRateLimiter functionality:

Migration to: spring-boot: 2.3.4.RELEASE / **spring-cloud: Hoxton.SR8**

ERROR 1 --- [boundedElastic-5] reactor.core.scheduler.Schedulers: Scheduler worker in group main failed with an uncaught exception reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalArgumentException: Unable to find GatewayFilterFactory with name RequestRateLimiter

Caused by: java.lang.IllegalArgumentException: Unable to find GatewayFilterFactory with name RequestRateLimiter
	at org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator.loadGatewayFilters(RouteDefinitionRouteLocator.java:187)

Removing the configuration of the **RequestRateLimiter** functionality presented below starts to work perfectly.
```
- name: RequestRateLimiter
  args:
	redis-rate-limiter.replenishRate: 150
	redis-rate-limiter.burstCapacity: 165
```

**Before** the migration with the following settings it was perfect: spring-boot: 2.2.8.RELEASE / **spring-cloud: Hoxton.SR5**

application-production.yaml

```
spring:
  cloud: 
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            series: SERVER_ERROR 
            methods: GET
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false
        
      discovery:
        locator:
          enabled: true     
          route-id-prefix: api-
          lower-case-service-id: true
          include-expression: true
          url-expression: "'http://' + serviceId + '.' + metadata['namespace']  + ':' + port"          
          predicates:
            - name: Path
              args:
                pattern: "'/'+serviceId+'/**'"   
          filters:
            - name: CircuitBreaker
              args:
                name: serviceId                
            - name: RewritePath
              args: 
                regexp: "'/' + serviceId + '/(?<remaining>.*)'"
                replacement: "'/${remaining}'"
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 150
                redis-rate-limiter.burstCapacity: 165
          
    kubernetes:
      enabled: true
      discovery:
        enabled: true
        catalog-services-watch:
          enabled: true
        catalogServicesWatchDelay: 30000
        all-namespaces: true
        service-labels:
          ambiente: "prd"
          gateway: "default"
```
