### ISSUE TITLE
How to disable KubernetesClientAutoConfiguration

### ISSUE THREAD

**Issue by akefirad** [spring-cloud/spring-cloud-kubernetes#713]
**Describe the bug**
I set the following properties in my application properties files:
```yaml
spring:
  cloud:
    kubernetes:
      enabled: false
      config:
        enabled: false
```
But I still see `org.springframework.cloud.kubernetes.client.KubernetesClientAutoConfiguration#apiClient` getting called. Am I missing something?

**Sample**
[k8s-config.zip](https://github.com/spring-cloud/spring-cloud-kubernetes/files/5744683/k8s-config.zip)

**Comment by wind57** [comment]
are you sure the problem is not somewhere else in your code? that should not happen, as the `@Configuration` responsible for the `ApiClient` has the annotation `ConditionalOnKubernetesEnabled`:

```
@ConditionalOnProperty(value = "spring.cloud.kubernetes.enabled", matchIfMissing = true)
public @interface ConditionalOnKubernetesEnabled {

}
```

**Comment by akefirad** [comment]
I'm pretty sure. The sample project is a clean one, no custom code. And yes, I checked the code as well and saw the condition. That's why I'm 😕. Also another thing that is really strange, I can't disable logs of `KubernetesClientUtils`:
```yaml
logging.level:
  org.hibernate.SQL: info # debug to see sql logs
  org.hibernate.type: info
  org.hibernate.type.descriptor.sql.BasicBinder: info # trace to see sql logs
  org.hibernate.type.descriptor.sql.BasicExtractor: info # trace to see sql logs
  org.springframework.cloud.kubernetes.client.KubernetesClientUtils: off
```
All other above log configurations work just fine except for `KubernetesClientUtils`.
Any idea?
