### ISSUE TITLE
Cannot disable api calls when only using secrets with path

### ISSUE THREAD

**Issue by jemag** [spring-cloud/spring-cloud-kubernetes#715]
**Describe the bug**
When mounting secrets from a path, there does not seem to be a way to disable calls made to the API server, even if they are not necessary to accomplish the task.

 Excluding kubernetes discovery does not help:
``` groovy
    implementation('org.springframework.cloud:spring-cloud-starter-kubernetes-config:1.1.7.RELEASE') {
        exclude group: 'org.springframework.cloud', module: 'spring-cloud-kubernetes-discovery'
    }
```
or disabling any other feature and setting enable-api to false:
``` yaml
spring:
  application:
    name: systeminformer
  cloud:
    kubernetes:
      discovery:
        enabled: false
      reload:
        enabled: false
      secrets:
        paths: /etc/secrets/systeminformer-spc
        enabled: true
        enable-api: false
      enabled: true
      config:
        enabled: false

```
Calls will still be made to the API Server. This is an issue because 
- These calls are not needed to load secrets from a volume path
- These calls will trigger useful runtime security monitoring:
![image](https://user-images.githubusercontent.com/7985687/103791474-7a827180-5010-11eb-8858-6d74ad72accf.png)

Muting the alert on the monitoring tool would be bad practice as it would remove visibility into a useful security risk. Not muting the alert will flood potential real issues in a sea of false positives.

Overall, I am not sure if this is the intended behavior (still making calls to the API server despite the current configuration) or a bug. Either way, I think a way to disable any call from being made to the API server would be great.
