### ISSUE TITLE
k8s - configmap adds watch for all available configmap in the namespace.

### ISSUE THREAD

**Issue by nareshgnT** [spring-cloud/spring-cloud-kubernetes#752]
**Describe the bug**
Version 2.0.1
apps needs only configmap injection so included only `implementation group: 'org.springframework.cloud', name: 'spring-cloud-starter-kubernetes-client-config'` and bootstarp.yml config as follows

```yml
spring:
  application:
    name: my-test-app
  cloud:
    loadbalancer:
      cache:
        enabled: false
    kubernetes:
      enabled: ${KUBERNETES_CONFIG_ENABLED:false}
      reload:
        enabled: ${KUBERNETES_CONFIG_ENABLED:false}
      config:
        enabled: ${KUBERNETES_CONFIG_ENABLED:false}
        name: ${SPRING_APPLICATION_NAME:unknown}
        namespace: default
      discovery:
        enabled: false
      loadbalancer:
        enabled: false
```
when we start the application we can see logs saying its adding watch for all the configmap that are available in the namespace.
we have 1000's of configmap so worried about any performance issue it may cause.
 
example
```
CongifMap app1 was added.
Configuration change was not detected.
CongifMap app2 was added.
Configuration change was not detected.
CongifMap app3 was added.
Configuration change was not detected.
CongifMap app4 was added.
Configuration change was not detected.
CongifMap app5 was added.
Configuration change was not detected.
...
```
 Why not only add watch for configmap that default/mentioned or filter before adding the watch?

**Comment by ryanjbaxter** [comment]
We could probably watch specific configmaps and secrets, for example ones specified via configuration or via an annotation/label.

**Comment by UnleashSpirit** [comment]
Hi, just to pop up this topic
I have the same problem
It's logs every 2s ^^

If I set `spring.cloud.kubernetes.config.enabled=false` problem 'solved' but I loose the hotreload function

**Comment by Kostyaesikov** [comment]
Any updates here?

**Comment by ryanjbaxter** [comment]
None yet, but if you are interested in helping out and submitting a PR that would be welcome

**Comment by wind57** [comment]
This one is a bit tricky. First of all, I'd like to work on this one and fix it, but first we need to establish some rules (that I will kindly request approval for).

There are two ways we can listen for changes (I'll exclude watcher from this perspective entirely):

- pool configmaps/secrets on some interval
- use informers to receive events when something changes.

In the first case, we get the existing state of PropertySources and the k8s state; if there are diffs, reload/restart/close context (whatever is configured).

In the second case, currently, we only listen to the "current" (or configured) namespace. This is a first big difference, since we will obviously miss events if changes happen in configmaps outside this namespace. I am kind of surprised this has not been raised as an issue yet (unless I missed it).
The other part here is that we can't replicate the logic that pooling does, since we need to know upfront what we want to watch for and where. As such, I am proposing this:

- users can specify the namespaces they want to watch configmaps/secrets. If they do not specify it, we will use : https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#namespace-resolution. Neither of this is currently implemented.
- if they provide the namespace(s), we will create an informer for each of those namespace separately and watch changes only in those.
- users can narrow the configmaps/secrets that they are interested in by providing `spring.cloud.kubernetes.informer.enabled=true` label. Initially, I thought about letting users specify this name, but it complicates things for us a bit, and it does not really matter either: all we need is a marker to distinguish stuff. It also has to be a label because k8s does not allow searching by annotations. 

@ryanjbaxter if you agree with the above or have any comments, let me know, and I'll start implementing this.

**Comment by ryanjbaxter** [comment]
Sounds good to me

**Comment by UnleashSpirit** [comment]
Hi, 
I need a bit of explanation about the fix.
If I understand well, with the config, spring will monitor changes in all configmap of the specified namespace or only those with label `spring.cloud.kubernetes.config.informer.enabled: true` ?

But lets say I have two (or more) spring apps in th esame namespace each with it's own configmap.
app A depends on cm A  and app B depends on cm B
So I need to monitor both cm A & B, so both will have the label. But I don't want app A to reload if changes happens in cm B (while app B needs to reload).
Does this fix offer me solution or no (not yet ? :))

**Comment by wind57** [comment]
> If I understand well, with the config, spring will monitor changes in all configmap of the specified namespace or only those with label spring.cloud.kubernetes.config.informer.enabled: true ?

you can specify both:

```
spring:
  application:
    name: event-reload
  cloud:
    kubernetes:
      reload:
        enabled: true
        strategy: shutdown
        mode: event
        namespaces:
          - left
        monitoring-config-maps: true
```

this will watch configmaps in namespace `left` _and_ only those that have `spring.cloud.kubernetes.config.informer.enabled: true` label.

If you change `monitoring-config-maps: false` (default value), it will watch for _all_ configmaps in namespace `left`.

---

> But lets say I have two (or more) spring apps in th esame namespace each with it's own configmap.
app A depends on cm A and app B depends on cm B
So I need to monitor both cm A & B, so both will have the label. But I don't want app A to reload if changes happens in cm B (while app B needs to reload).

This is indeed not supported at this moment. It's actually doable if we let you specify labels yourself. So for example, in `appA` you want say : "what configmaps that only match labels = { ... }" and the same for `appB`. This way this can be distinguished. If you would like such support, I would encourage you to open a new defect. Event better if you could contribute with a fix (I could guide you a little). 

Thank you.
