### ISSUE TITLE
Get 503 response with spring cloud k8s 

### ISSUE THREAD

**Issue by GitHub-Yann** [spring-cloud/spring-cloud-kubernetes#771]
**Describe the bug**
There is 503 response returned when I try to visit the service in another k8s namespace.

**Sample**

pom.xml file
spring-cloud-gateway : 2.2.5.RELEASE
spring-cloud : Hoxton.SR8
spring-cloud-kubernetes : 1.1.6.RELEASE

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.10.RELEASE</version>
		<relativePath />
	</parent>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-gateway</artifactId>
		</dependency>
		<dependency>
                       <groupId>org.springframework.cloud</groupId>
                       <artifactId>spring-cloud-kubernetes-core</artifactId>
                </dependency>
                <dependency>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-kubernetes-discovery</artifactId>
                </dependency>
                <dependency>
                    <groupId>org.springframework.cloud</groupId>
                    <artifactId>spring-cloud-starter-kubernetes-ribbon</artifactId>
                </dependency>
                <dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-kubernetes-loadbalancer</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

application.yml 
```
server.port: 9891
spring:
  cloud:
    kubernetes:
      loadbalancer:
        mode: SERVICE
      discovery:
        all-namespaces: true
    gateway:
      routes:
      - id: route-y02
        uri: lb://backend-demo-svc:8855
        predicates: 
        - Path=/demoy02/**
        filters: 
        - StripPrefix=1
      - id: route-y03
        uri: lb://backend-demo-svc.gateway:8855
        predicates: 
        - Path=/demoy03/**
        filters: 
        - StripPrefix=1
      - id: route-y04
        uri: lb://backend-demo-svc-kkk
        predicates: 
        - Path=/demoy04/**
        filters: 
        - StripPrefix=1
      - id: route-y05
        uri: lb://backend-demo-svc-kkk.vc-namespace
        predicates: 
        - Path=/demoy05/**
        filters: 
        - StripPrefix=1
      - id: route-y06
        uri: lb://backend-demo-svc-kkk.vc-namespace.svc.cluster.local
        predicates: 
        - Path=/demoy06/**
        filters: 
        - StripPrefix=1
```

my deployment topology:
(1) backend-demo-svc (k8s service with port 8855)  and gateway are deployed in the same namespace, e.g: gateway
(2) backend-demo-svc-kkk (k8s service with port 80) is deployed in another namespace, e.g: vc-namespace

I hava 5 routes to do testing
(1) route-y02 : it returns correct response
(2) route-y03 : it returns 503 with message Unable to find instance for backend-demo-svc.gateway
(3) route-y04 : it returns 503 with message Unable to find instance for backend-demo-svc-kkk
(4) route-y05 : it returns 503 with message Unable to find instance for backend-demo-svc-kkk.vc-namespace
(5) route-y06 : it returns 503 with message Unable to find instance for backend-demo-svc-kkk.vc-namespace.svc.cluster.local

I prepared a controller to print the instances, seems it's ok , the instance of  backend-demo-svc-kkk is also printed.
code like : 
```
@GetMapping("gateway/services")
	public List<String> services() {

		List<String> serviceIds = this.discoveryClient.getServices();
		for (String id : serviceIds) {
			List<ServiceInstance> ins = this.discoveryClient.getInstances(id);
                        ......print instance detail
```

Is there any suggestion on this ?

**Comment by ryanjbaxter** [comment]
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by GitHub-Yann** [comment]
Hi , 
you can refer the sample from https://github.com/GitHub-Yann/gateway-k8s.
It's a zip file.

(1)you can unzip the file.
(2) you can change the application-gatewaypeer1.yml , set your target service
![image](https://user-images.githubusercontent.com/9768021/113253396-c5521380-92f7-11eb-84c0-d6e866dd23c3.png)

(3)build the jar file : mvn clean package -Dmaven.test.skip=true
(4)build the image
(5)deploy

**Comment by ryanjbaxter** [comment]
The sample only has the gateway not the service it points to so it is hard to use this sample.

What is the name of the kubernetes service for the service you are trying to route requests to?

**Comment by GitHub-Yann** [comment]
This is my deployment toplogic 

![图片](https://user-images.githubusercontent.com/9768021/113310804-31a23680-933b-11eb-9460-cd45e84587d4.png)

**Comment by ryanjbaxter** [comment]
I dont think you need to specify the namespace in the `lb://` url, just put the service name.

**Comment by GitHub-Yann** [comment]
I tried, you can refer to the route : route-y000000000000003 in the image with blue background  color.

**Comment by ryanjbaxter** [comment]
Please provide the backend service to deploy along side the gateway to test

**Comment by GitHub-Yann** [comment]
Hi ,
The backend demo is here : https://github.com/GitHub-Yann/gateway-k8s

backend-service-clear.zip

**Comment by ryanjbaxter** [comment]
Looking at the zips, I don't see any way to build images or deployment yamls, can you please provide those?

**Comment by GitHub-Yann** [comment]
Hi @ryanjbaxter 

Thanks for your reply.

## Steps:
(1) Please create 2 namespaces: gateway and vc-namespace
(2) In the gateway namespace, please deploy the gateway demo and backend demo
(3) In the vc-namespace namespace, please deploy the backend demo
(4) I have pushed the 2 images into docker hub

## k8s deployments
```yaml
- - - - - - - - - - - - - - - - - -below is the backend demo deployment
#backend-demo-xyz
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-demo-xyz
  namespace: gateway
  labels:
    app: backend-demo-xyz
spec:
  replicas: 1            
  selector:
    matchLabels:
      app: backend-demo-xyz      
  template:
    metadata:
      labels:
        app: backend-demo-xyz    
    spec:
#      imagePullSecrets:
#        - name: regcred    
      containers:
        - name: backend-demo-xyz
          image: akaxb/backend-demo:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9955
---            
#service
apiVersion: v1
kind: Service
metadata:
# To make it easier to distinguish, in gateway namespace use backend-demo-xyz-svc1 and in vc-namespace please use backend-demo-xyz-svc2, also my gateway route is defined as this
  name: backend-demo-xyz-svc1  
  namespace: gateway
spec:
  selector:
    app: backend-demo-xyz                
  ports:
    - protocol: TCP
      port: 7755
      targetPort: 9955
```
```yaml
- - - - - - - - - - - - - - - - - -below is the gateway demo deployment
#gateway-k8s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-k8s
  namespace: gateway
  labels:
    app: gateway-k8s
spec:
  replicas: 1            
  selector:
    matchLabels:
      app: gateway-k8s      
  template:
    metadata:
      labels:
        app: gateway-k8s    
    spec:
#      imagePullSecrets:
#        - name: regcred    
      containers:
        - name: gateway-k8s
          image: akaxb/gateway:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9891
---            
#service
apiVersion: v1
kind: Service
metadata:
  name: gateway-k8s-svc
  namespace: gateway
spec:
  selector:
    app: gateway-k8s                
  ports:
    - protocol: TCP
      port: 9891
      targetPort: 9891
      nodePort: 31234
  type: NodePort
```

## other info:
(1) below is my gateway routes
```json
[{
	"predicate": "Paths: [/demoy01/**], match trailing slash: true",
	"route_id": "route-y000000000000001",
	"filters": ["[[StripPrefix parts = 1], order = 1]"],
	"uri": "lb://backend-demo-xyz-svc1:7755",
	"order": 0
},
{
	"predicate": "Paths: [/demoy02/**], match trailing slash: true",
	"route_id": "route-y000000000000002",
	"filters": ["[[StripPrefix parts = 1], order = 1]"],
	"uri": "lb://backend-demo-xyz-svc1.gateway:7755",
	"order": 0
},
{
	"predicate": "Paths: [/demoy03/**], match trailing slash: true",
	"route_id": "route-y000000000000003",
	"filters": ["[[StripPrefix parts = 1], order = 1]"],
	"uri": "lb://backend-demo-xyz-svc2:7755",
	"order": 0
},
{
	"predicate": "Paths: [/demoy04/**], match trailing slash: true",
	"route_id": "route-y000000000000004",
	"filters": ["[[StripPrefix parts = 1], order = 1]"],
	"uri": "lb://backend-demo-xyz-svc2.vc-namespace:7755",
	"order": 0
},
{
	"predicate": "Paths: [/demoy05/**], match trailing slash: true",
	"route_id": "route-y000000000000005",
	"filters": ["[[StripPrefix parts = 1], order = 1]"],
	"uri": "http://backend-demo-xyz-svc2.vc-namespace:7755",
	"order": 0
}]
```
(2)topologic
![image](https://user-images.githubusercontent.com/9768021/114964261-f0646780-9ea0-11eb-8736-e8ab338d46b2.png)

**Comment by ryanjbaxter** [comment]
All this information should be included in the samples instead of in the issue.

**Comment by GitHub-Yann** [comment]
Hi ,

### for point 2 , I changed my k8s deployment file, set the k8s svc port of the backend-demo-service as 80 , so my routes are changed as below : 
```yaml
spring:
  cloud:
    kubernetes:
      loadbalancer:
        mode: SERVICE
      discovery:
        all-namespaces: true
    gateway:
      routes:
      - id: route-y000000000000001
        uri: lb://backend-demo-xyz-svc1
        predicates: 
        - Path=/demoy01/**
        filters: 
        - StripPrefix=1
      - id: route-y000000000000002
        uri: lb://backend-demo-xyz-svc1.gateway
        predicates: 
        - Path=/demoy02/**
        filters: 
        - StripPrefix=1
      - id: route-y000000000000003
        uri: lb://backend-demo-xyz-svc2
        predicates: 
        - Path=/demoy03/**
        filters: 
        - StripPrefix=1
      - id: route-y000000000000004
        uri: lb://backend-demo-xyz-svc2.vc-namespace
        predicates: 
        - Path=/demoy04/**
        filters: 
        - StripPrefix=1
      - id: route-y000000000000005
        uri: http://backend-demo-xyz-svc2.vc-namespace
        predicates: 
        - Path=/demoy05/**
        filters: 
        - StripPrefix=1
```

The both gateway and backend-demo-service projects you can refer from https://github.com/GitHub-Yann/gateway-k8s , also there are dockerfile content in the readme file.

### for point1 , I tried 2 round testings:
- round 1 :  I remain the spring-cloud-kunernetes-ribbon dependency in the pom, below is the result for the 5 routes
![2021-5-28 8-30-34-ribbon](https://user-images.githubusercontent.com/9768021/119914690-5a3d5a00-bf93-11eb-94fd-e5db11b0092b.png)

- round 2 :  I remain the spring-cloud-kubernetes-loadbalancer dependency in the pom, below is the result for the 5 routes , **_even the 1st route is return 500 error_**.
![2021-5-28 8-40-50-loadbalancer](https://user-images.githubusercontent.com/9768021/119914719-6b866680-bf93-11eb-986d-2a424b049458.png)
