### ISSUE TITLE
spring.config.activate.on-profile doesn't work in ConfigMap

### ISSUE THREAD

**Issue by vprudnikov** [spring-cloud/spring-cloud-kubernetes#778]
Versions:
Spring Boot: 2.4.4
spring-cloud-dependencies: 2020.0.2

Maven dependencies:
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-dependencies</artifactId>
    <version>${spring-cloud-dependencies.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-kubernetes-fabric8-istio</artifactId>
</dependency>
```

ConfigMap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
  namespace: my-namespace
data:
  application.yml: |-
    spring.profiles.group:
      all-mock:
        - int-mock
    integration:
      baseUrl: NOT_DEFINED
    ---
    spring.config.activate.on-profile: int-mock
    integration:
      baseUrl: http://localhost:8080/
---
```

When I run my app without any active profile then I expect that the `integration.baseUrl` gets `NOT_DEFINED` value, however, it is set to `http://localhost:8080/`

Another problem is that the `spring.profiles.group.` feature doesn't work either: the listed profiles are simply ignored when I activate the `all-mock` profile.

Could you please help?
Thank you!

**Comment by ryanjbaxter** [comment]
There are new properties in Spring Boot 2.4.x and I dont think we have taken them into account when loading Config Maps as property sources using the API.

As a workaround you could mount these ConfigMaps as volumes and have Boot load them directly.  This is actually the preferred method anyways over using the K8S API.

**Comment by vprudnikov** [comment]
@ryanjbaxter , thanks for the reply!

Do you have any link to documentation that describes the preferred method you mentioned?

**Comment by ryanjbaxter** [comment]
From a K8S perspective this is what you would have to do
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#add-configmap-data-to-a-volume

Then from a Spring Boot perspective you can do something like this https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-files-configtree

**Comment by vprudnikov** [comment]
Thanks, @ryanjbaxter 

Just one question: does it mean that you guys are going to fix this issue in the 2020.0.3 version?

**Comment by ryanjbaxter** [comment]
Not necessarily, if we can get to it we will fix it but no guarantee.

**Comment by mmaeller** [comment]
Hi @ryanjbaxter, 
Got a related issue without `spring.profiles.group`.

application.yaml with default value for all profiles
```yaml
someProperty: value
```

confIgMap with profile related values
```yaml
    ---
    spring:
      config:
        activate:
          on-profile: myProfile1
    someProperty: value1
    ---
    spring:
      config:
        activate:
          on-profile: myProfile2
    someProperty: value2
```

When I start the application (2.4.5, 2020.0.2 and spring-cloud-starter-kubernetes-fabric8-config) with profile "myProfile1" then `value2` will be used.
When I switch back to `spring.profiles` it works as expected and `value1` will be used.

Regards
Matthias
