### ISSUE TITLE
Config watcher didn't response to configmap change after 45 minutes

### ISSUE THREAD

**Issue by neo-feng** [spring-cloud/spring-cloud-kubernetes#837]
**Describe the bug**
I'm using config watcher to enable auto refresh for my  spring cloud microservices deployed in aws EKS.
Config watcher is also deployed in EKS. 
It works fine when config watcher was just deployed, however, after 40 minutes, when I modified the configmap again to test it again, config watcher didn't response, no logs at all.

Config watcher version:  2.1.0-SNAPSHOT
Spring boot version: 2.4.4
JDK: 1.8.0_282

**Sample**
project link:  https://github.com/neo-feng/configdemo 
you may find all information from link above.

pom dependencies:
```
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
            <version>${spring.cloud.config.version}</version>
        </dependency>
	</dependencies>
```

bootstrap.yml
```
spring:
  application:
    name: demo-service
  cloud:
    kubernetes:
      config:
        #enabled: true
        sources:
          - namespace: default
            name: ${spring.application.name}

server:
  port: 8080
```
reproduce steps:
- deploy the application and test it successfully according to readme.md in the link above
- after 40 minutes, test it again -- change the configmap and watch logs
- you'll see config watcher has no response, no logs at all

It seems config watcher was disconnected with kubernetes after 40 minutes, while it still works well after 20 minutes, has no idea how to proceed, any suggestion will be appreciated.
