### ISSUE TITLE
multiple ConfigMaps with the same key

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#843]
Suppose I have a ConfigMap like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-single-file-duplicates
  namespace: spring-k8s
data:
  application.yaml: |
    mykey: myvalue
  application.properties: |
    mykey=myvalue
```

And in `bootstrap.yaml`:

```
spring:
  cloud:
    kubernetes:
      config:
        namespace: spring-k8s
        sources:
          - name: config-map-single-file-duplicates
```

So when starting the application (with `org.springframework.cloud:spring-cloud-kubernetes-fabric8-config` as dependency), I get an Exception in the form of :

```
java.lang.IllegalStateException: Duplicate key myvalue
        at org.springframework.cloud.kubernetes.commons.config.PropertySourceUtils.lambda$throwingMerger$5(PropertySourceUtils.java:112) .....
``` 

which makes perfect sense. This hits the `throwingMerger` [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-commons/src/main/java/org/springframework/cloud/kubernetes/commons/config/ConfigMapPropertySource.java#L86).

---

On the other hand, if I have _two_ config maps:

`config-map-multiple-maps-duplicate-entries.yaml`:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-multiple-maps-duplicate-entries
  namespace: spring-k8s
data:
  application.properties: |
    mykey1=value1
```

and `config-map-multiple-maps-duplicate-entries-kubernetes.yaml`:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-multiple-maps-duplicate-entries-kubernetes
  namespace: spring-k8s
data:
  application.properties: |
    mykey1=value2

```

Because the way [code processes these](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8ConfigMapPropertySource.java#L61)

the second config map will override every common property from the first one.  This looks fishy? I mean if there are more active profiles, this overridden properties will get messy. 

It seems to me that this is an artifact of an/a initial/previous implementation; I have looked at the documentation and I do not see this being mentioned. As such, I will express my opinion that this needs to be removed, specifically this part:

```
			if (environment != null) {
				for (String activeProfile : environment.getActiveProfiles()) {
					String mapNameWithProfile = applicationName + "-" + activeProfile;
					Map<String, String> dataWithProfile = getConfigMapData(client, namespace, mapNameWithProfile);
					result.putAll(processAllEntries(dataWithProfile, environment));
				}
			}
```
I see the same thing happening in [kubernetes-client](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-client-config/src/main/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigMapPropertySource.java) too, so I have a dilemma of what this serves. 

Thank you.
