### ISSUE TITLE
Multiple using Configmap does not work

### ISSUE THREAD

**Issue by ivanfomkin** [spring-cloud/spring-cloud-kubernetes#851]
**Describe the bug**
I'm try to use Spring Cloud Kubernetes for getting config from ConfigMab

**Sample**
my pom.xml contain thsi dependencie:
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-kubernetes-fabric8-config</artifactId>
            <version>2.0.3</version>
        </dependency>
```
My bootstrap.yml:
```
spring:
  application:
    name: umtapprocessing
  cloud:
    kubernetes:
      config:
        namespace: tppdev
        name: globalconfig
        sources:
          - name: umtapconfig
          - name: queueconfig
          - name: tppconfig
          - name: globalconfig
```

My globalconfig is work fine. but other configurations, f.e. tppconfig or umtapconfig doesn't work and i'm getting exception when i try create beans for use them:
```
Error creating bean with name 'bklFileFinder' defined in URL [jar:file:/opt/app.jar!/BOOT-INF/classes!/ru/mycompany/umtapprocessingservice/services/bkl/BklFileFinder.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bklFileProcessor' defined in URL [jar:file:/opt/app.jar!/BOOT-INF/classes!/ru/mycompany/umtapprocessingservice/services/bkl/BklFileProcessor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'bklFileParser' defined in URL [jar:file:/opt/app.jar!/BOOT-INF/classes!/ru/mycompany/umtapprocessingservice/services/bkl/BklFileParser.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shiftService': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'tpp.dateRangeToSearchShift.days' in value "${tpp.dateRangeToSearchShift.days}"
```
This is my globalconfig (part of them for example):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: globalconfig
  namespace: tppdev
data:
  application.yaml: |-
    spring:
      autoconfigure:
        exclude: '#{"${spring.rabbitmq.enabled:}".equals("false")?"org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration":"io.awspring.cloud.autoconfigure.messaging.SqsAutoConfiguration"}'
      datasource:
        url: ${DATABASE_URL}
```

This is my tppconfig:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: tppconfig
  namespace: tppdev
data:
  application.yaml: |-
    tpp:
      tit:
        enabled: false
```

What am I doing wrong? Or this is a bug?
Thank you!
