### ISSUE TITLE
[Question] can I put properties for spring cloud bus in confimap?

### ISSUE THREAD

**Issue by Mongolian1** [spring-cloud/spring-cloud-kubernetes#871]
```
spring:
  cloud:
      bus:
        refresh:
          enabled: false #disable this because we are going to provide our own refresh listener for testing purposes
        enabled: false
```
Hello, Can i put the above block of properties in configmap and refresh config with kafka and spring cloud kubernetes config watcher.
But I am concerned about that once i set spring.cloud.bus.refresh.enabled = false I can not make my app reload the conifg with kafka and spring cloud kubernetes config watcher anymore.
Thanks a lot !
