### ISSUE TITLE
Configuration-Watcher not working for secrets?

### ISSUE THREAD

**Issue by boehb-efs** [spring-cloud/spring-cloud-kubernetes#895]
**Describe the bug**

I'm trying to enable the spring cloud kubernetes configuration watcher for secrets.

More specifically:

I have a service providing information stored in a secret stored and required by another service.

However, it does not appear to work. When trying to update a configmap, everything works fine. Updating a volume-mounted secret will lead to updating the files within the volume-mount, however, the refresh is not being executed!

**Sample**

Setup:

- the Component reading the secret (ConnectionProvider) is marked as @ConfigurationProperties.
    ```java
    @Component
    @ConfigurationProperties
    public class ConnectionProvider {

        private Map<String, String> storageconnections;

        public Map<String, String> getStorageconnections() {
            return storageconnections;
        }
    }
    ```
- the secret is loaded via volumemount:
    ```yaml
     ...
      containers:
        - volumeMounts:
            - name: secret-mount
              mountPath: "/etc/secrets"
              readOnly: true
            - name: storage-secrets
              mountPath: "/etc/storage-secrets"
              readOnly: true
            - name: db-secrets
              mountPath: "/etc/db-secrets"
              readOnly: true
          ...
      volumes:
        - name: secret-mount
          secret:
            secretName: eventhub-secret
        - name: storage-secrets
          secret:
            secretName: accessmanager-storage-connections
        - name: db-secrets
          secret:
            secretName: accessmanager-secret-db
      ...
    ```
- the secret is integrated via bootstrap.yml like this (where ```accessmanager-storage-connections``` is the name of the secret being updated):
    ```yaml
      spring:
        application:
          name: accessmanager-storage-connections
        cloud:
          kubernetes:
          secrets:
            enabled: true
            paths:
              - /etc/secrets
              - /etc/storage-secrets
              - /etc/db-secrets
          config:
            name: accessmanager
            namespace: backend
          reload:
             enabled: true
             mode: event
    ```
- the secret contains the refresh-label:
    ```yaml
    apiVersion: v1
    kind: Secret
    metadata:
      labels:
        spring.cloud.kubernetes.secret: "true"
      name: accessmanager-storage-connections
      namespace: backend
    data: {}
    type: Opaque
    ```
- the refresh-endpoints are published:
    ```yaml
    management:
      endpoints:
        web:
          exposure:
            include: [
                prometheus,
                health,
                info,
                refresh,
                bus-refresh,
                beans,
                env
            ]
    ```
- deployment of configuration-watcher according the [example](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#deployment-yaml), tried with both version 2.0.1-SNAPSHOT and 2.0.4
- I also tried [different approaches](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#secrets-propertysource) when integrating secrets via bootstrap, however, only ```spring.cloud.kubernetes.secrets.name/spring.cloud.kubernetes.secrets.namespace``` and ```spring.cloud.kubernetes.secrets.paths``` worked, whereas, when integrating via ```spring.cloud.kubernetes.secrets.labels``` and ```spring.cloud.kubernetes.secrets.sources``` the secrets were not found.
- also, when manually refreshing via ```curl -X POST http://localhost:8090/actuator/refresh -d {} -H "Content-Type: application/json"```, new entries to the secret are being detected, however, deleted ones remain

To test the functionality: 
- edit the secret
- log the secret-parameters in scheduler:
    ```java
        @Scheduled(fixedDelay = 15000L)
        public void logConnections() {
            LOG.info("connections at " + ZonedDateTime.now());
            connProvider.getStorageconnections().entrySet().forEach(e -> LOG.info(e.getKey() + ": " + e.getValue()));
        }
    ```

**Comment by spring-cloud-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by boehb-efs** [comment]
Hi,
an minimal sample can be found at https://github.com/boehb-efs/configuration-watcher-demo

**Comment by ryanjbaxter** [comment]
A couple of issues with your sample...

1. The secret name, service name, and must match.  The configuration watcher will watch the secret for changes, if it sees a change than it will look up a service using the name of the secret and make an http request to `/refresh`.  Since your service name does not match the secret name the configuration watcher can't find the service and a request is not made.

2. Since you are not using the default actuator path you need to specify the actuator path as an annotation in the service metadata
```
apiVersion: v1
kind: Service
metadata:
  name: demo-secret2
  namespace: backend
  annotations:
    boot.spring.io/actuator: http://:8090/config-watcher-demo/actuator
spec:
  selector:
    app: config-watcher-demo
  ports:
    - port: 8090
```
