### ISSUE TITLE
Under a certain condition we will be reading the same secret multiple times

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#916]
Consider the configuration below:

```
spring:
   application:
       name: my-app
   cloud:
      kubernetes:
          secrets:
             enableApi: true
             namespace: spring-k8s
             sources:
             - labels:
                   a: b
             -labels:
                   c: d
```

Because of the way our code is set-up for finding such secrets, we will be reading a secret with name `my-app` _twice_. 

We have enforced reading unique secrets some time ago, but that is based on `name/namespace/labels`, since `labels` are different in the above case, that uniqueness does not apply here. 

Not only will we be reading it twice, but the overall decision of placing the `labels` inside the sources has its drawbacks. While working on a PR that is supposed to add some functionality, like appending the secret name to the properties from a secret (`useNameAsPrefix` that we already have implements in config maps), things started to complicate pretty fast. I am not going to go into the exact details (though if needed I gladly will), but besides fixing this issue, we must absolutely make a clear distinction between a NormalizedSource that is based on labels and one that is based on a secret name. 

I will come up with a proposal of what I mean soon.

**Comment by ryanjbaxter** [comment]
Will we read it twice because the secret contains both labels?

**Comment by wind57** [comment]
I'll explain it better, sorry for the confusion. 

```
namespace: spring-k8s
sources:
     - labels:
          a: b
     -labels:
          c: d
```

In our code we will compute 2 normalized sources:

```
namespace: spring-k8s
labels: {a=b}
```

and 

```
namespace: spring-k8s
labels: {c=d}
```

Notice, I am saying two `NormalizedSources`. Based on these two sources, we will compute two instances of : `Fabric8SecretsPropertySource` (same for k8s-native). Notice [here](https://github.com/spring-cloud/spring-cloud-kubernetes/blob/main/spring-cloud-kubernetes-fabric8-config/src/main/java/org/springframework/cloud/kubernetes/fabric8/config/Fabric8SecretsPropertySourceLocator.java#L72) how each of them will create the same `secretName` called `my-app`. 

So above normalized sources will create 2 `Fabric8SecretsPropertySource` that will look like:

```
name: my-app
namespace: spring-k8s
labels: {a=b}
```

and

```
name: my-app
namespace: spring-k8s
labels: {c=d}
```

This will end up reading `my-app` twice.
