### ISSUE TITLE
We won't be adding any more features to Ribbon.  Netflix has put it in maintenance.

### ISSUE THREAD

**Issue by damon008** [spring-cloud/spring-cloud-kubernetes#920]
We won't be adding any more features to Ribbon.  Netflix has put it in maintenance.

_Originally posted by @ryanjbaxter in https://github.com/spring-cloud/spring-cloud-kubernetes/issues/912#issuecomment-970189600_

@ryanjbaxter No, I mean adding the features of ribbon to the new LB, not add any more features to Ribbon. We hope use yaml or properties to set retries,timeout,policies and so on like it:
```
backend:
  ribbon:
    client:
      enabled: true
    ServerListRefreshInterval: 5000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 1000
  eager-load:
    enabled: true
    clients: cas-server-service
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
```
