### ISSUE TITLE
Configuration Watcher and Service Names

### ISSUE THREAD

**Issue by sdaskam1** [spring-cloud/spring-cloud-kubernetes#951]
For the Configuration Watcher to be able to make a refresh call to the application actuator, it looks like the Kubernetes service name has to match the spring boot app name (and config map name) or it won't be able to locate it to make the call. Currently, our services have a naming convention that is **[app-name]-svc** which is causing the Configuration Watcher to skip the update because it can't find a service with the correct name. Is there another way to tell the Configuration Watcher which service to look for without having to make the names match? We are just wondering if we are going to have to change the names of all our existing services to remove the -svc suffix.

**Comment by ryanjbaxter** [comment]
No they must match at the moment but this is a reasonable enhancement

**Comment by sdaskam1** [comment]
ok, thanks for the verification Ryan!

**Comment by mbaykara** [comment]
Hey @ryanjbaxter, the newer Spring boot version over 2.3.12 does not provide `/actuator/refresh` endpoint. Are you aware of it or do I miss some point?

**Comment by ryanjbaxter** [comment]
That endpoint has existed and continues to exist for a long while now, you might need to enable it and expose it

**Comment by mbaykara** [comment]
I did as follow but still getting 404. Is it wrong? @ryanjbaxter 
``` 
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
      restart:
        enabled: true
      refresh:
        enabled: true
```
