### ISSUE TITLE
Multiple config maps required for flagger when using config maps as property source

### ISSUE THREAD

**Issue by Hazmo** [spring-cloud/spring-cloud-kubernetes#968]
**Is your feature request related to a problem? Please describe.**
We are using flagger (https://flagger.app/) and have also implemented a way for our feature branches to be deployed using istio. 

This means we have multiple versions of our app deployed with suffixes in the name such as 'app-name', 'app-name-primary', 'app-name-branch'

This will require us to deploy a separate config map and update our bootstrap.yaml dynamically based on which feature branches are being deployed.

**Describe the solution you'd like**
All the versions of this app should only need one config map that updates them all. A way to do this would be to add label on the ConfigMap that then could be used in the boostrap.yaml to select the single configmap.

**Comment by ryanjbaxter** [comment]
Can you provide an example of what the ConfigMap would look like as well as what the bootstrap.yaml would look like?

**Comment by Hazmo** [comment]
Using my example of having 3 versions of the app -  **app_name**, **app-name-primary**, **app-name-branch**

ConfigMap
```
apiVersion: v1
kind: ConfigMap
name: app-name-primary
metadata:
  labels:
    spring.cloud.kubernetes.config: "true"
    spring.cloud.kubernetes.label: "app-name"
data:
  properties.yaml: |-
    {{range .Files.Lines "properties.yaml"}}
      {{ . }}
    {{ end }}
```

bootstrap.yaml
```
spring:
  application:
    name: app-name-primary
  cloud:
    kubernetes:
        sources:
          - label: app-name
```

This basically allows a one to many relationship between a ConfigMap and many apps. Having another look at the issues, this issue is the same as #937
