### ISSUE TITLE
Does not update the value from the config

### ISSUE THREAD

**Issue by lionchi** [spring-cloud/spring-cloud-kubernetes#970]
deployament.yaml
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-reader-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-with-kubernetes-config
data:
  math_max: "10"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: provider-service-with-kubernetes-config
data:
  application.yml: |-
    math:
      max: 10000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-with-kubernetes-deployment
spec:
  selector:
    matchLabels:
      name: service-with-kubernetes
  template:
    metadata:
      labels:
        name: service-with-kubernetes
    spec:
      containers:
        - name: service-with-kubernetes
          image: lionchi/service-with-kubernetes:latest
          ports:
            - containerPort: 8080
          env:
            - name: MATH_MAX
              valueFrom:
                configMapKeyRef:
                  name: service-with-kubernetes-config
                  key: math_max
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-service-with-kubernetes-deployment
spec:
  selector:
    matchLabels:
      name: discovery-service-with-kubernetes
  template:
    metadata:
      labels:
        name: discovery-service-with-kubernetes
    spec:
      containers:
        - name: discovery-service-with-kubernetes
          image: lionchi/discovery-service-with-kubernetes:latest
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              port: 9090
              path: /actuator/health/liveness
          readinessProbe:
            httpGet:
              port: 9090
              path: /actuator/health/readiness
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: service-with-kubernetes-autoscaling
spec:
  scaleTargetRef: 
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: service-with-kubernetes-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: discovery-service-with-kubernetes-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: service-with-kubernetes-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-with-kubernetes-service
spec:
  selector: 
    project: service-with-kubernetes
  ports:
    - name: service-with-kubernetes-listener
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service-with-kubernetes-service
spec:
  selector: 
    project: discovery-service-with-kubernetes
  ports:
    - name: discvovery-service-with-kubernetes-listener
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: NodePort
```

applicayion.yml
```
spring:
  cloud:
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        enabled: true
        sources:
          - name: provider-service-with-kubernetes-config`
```

Why is the MATH_MAX value not updated in the service after changing it in ConfigMap ?
