### ISSUE TITLE
Incorrect usage of useNameAsPrefix and explicitPrefix when used with profile based sources

### ISSUE THREAD

**Issue by wind57** [spring-cloud/spring-cloud-kubernetes#995]
Suppose there are two config maps currently deployed:

- `configMapA` that has `pass=123`
- `configMapA-dev` that has `pass=456`

Users specify reading them like this:

```
spring:
  cloud:
    kubernetes:
      config:
        sources:
          - name: configMapA
             useNameAsPrefix: true
             includeProfileSpecificSources: true
```

Of course, `dev` profile is active, too. 

At the moment, we will compute 2 property sources, one for `configMapA` and one for `configMapA-dev`. Both of them will use the same prefix, though : `configMapA`. Same thing would be true if we would use `explicitPrefix` instead of `useNameAsPrefix`. 

I wonder if `useNameAsPrefix` and `explicitPrefix` should be profile aware too. If so, that would mean that we must generate property sources like this:

`configMapA.pass=123` and `configMapA-dev.pass=456`. 

Currently, we will generate two property sources, with : `configMapA.pass=123` and `configMapA.pass=456`; which one will get to be used depends on the order, kind of wrong.

We have not received such an issue, but looks a totally valid case to me. Let me know what you think about this, thank you.
